'use strict';

/* ==========================================================================
   STRINGS — Übersetzungstexte DE/EN/PL für data-i18n* (siehe t()/
   applyTranslations() in app.js). AP-D (ARCHITEKTUR-PLAN.md): mechanisch
   trivial auszulagern, aber semantisch an das data-i18n-Markup in index.html
   gekoppelt — deshalb vorher der Schlüsselparitäts-Selbsttest in
   runSelfTests() (DE/EN/PL exakt dieselben Schlüssel). Verwaiste Schlüssel
   einmalig vor der Auslagerung statisch geprüft (Markup + t()-Aufrufstellen
   in app.js, inklusive der wenigen mit zusammengesetztem statt wörtlichem
   Schlüssel) — keine gefunden.

   t() und applyTranslations() bleiben in app.js: beide hängen an settings
   bzw. am DOM und sind damit kein Blatt. Dieses Modul ist reine Daten, ohne
   jede Logik.
   ========================================================================== */

export const STRINGS = {
  de: {
    'nav.songs': 'Songs',
    'nav.playlists': 'Setlisten',
    'nav.player': 'Player',
    'nav.settings': 'Einstellungen',

    'tabs.loops': 'Loops',
    'tabs.rec': 'REC',
    'tabs.lyrics': 'Lyrics',
    'tabs.notes': 'Notes',
    'scores.hintLabel': 'Noten verfügbar',
    'scores.modalTitle': 'Noten',

    'settings.importBtn': 'Songs importieren',
    'settings.personal.title': 'Make it yours!',
    'settings.personal.behaviorTitle': 'Verhalten',
    'settings.personal.displayTitle': 'Anzeige',
    'settings.personal.tabHint': 'Reiter, der beim Öffnen eines Songs zuerst zu sehen ist.',
    'settings.personal.tabGroupAria': 'Standard-Reiter im Player',
    'settings.personal.language': 'Sprache',
    'settings.personal.accent': 'Akzentfarbe',
    'settings.personal.presentTitle': 'Textanzeige für andere',
    'settings.personal.presentHint': 'Farbe der großen Vollbildanzeige zum Mitlesen (Vollbild-Knopf beim Liedtext).',
    'settings.personal.presentThemeDark': 'Weiß auf Schwarz',
    'settings.personal.presentThemeLight': 'Schwarz auf Weiß',
    'settings.personal.searchTitle': 'Song-Suche',
    'settings.personal.searchHint': 'Dienst für das Lupen-Symbol im Player. Langes Halten fragt einmalig nach einem anderen Dienst.',
    'settings.personal.searchPrivacyHint': 'Beim Antippen der Lupe im Player gehen Songtitel (und, falls hinterlegt, der Interpret) an den hier gewählten Dienst.',

    'songsearch.dialogTitle': 'Externe Suche',
    'songsearch.dialogPrefix': 'Öffnet ',
    'songsearch.dialogSuffix': ' und sendet den Songtitel dorthin, um danach zu suchen.',
    'songsearch.dialogServiceLabel': 'Dienst',
    'songsearch.dialogOk': 'Passt',
    'songsearch.dialogCancel': 'Dann nicht',

    'settings.voices.title': 'Meine Stimmen',
    'settings.voices.hint': 'Mehrfachauswahl möglich, für alle, die zwischen Stimmen wechseln. Bestimmt, welche Spuren beim Import vorausgewählt sind und welche Stimme der Player zuerst zeigt.',

    'settings.lightshow.title': 'Lichtshow',
    'settings.lightshow.hint': 'Acht kleine Bühnen-Einlagen für den Auftritt: Vollbild-Lichtfarben, die jede Stimme als eigenen Block inszenieren und über die Systemuhr synchron laufen.',
    'settings.lightshow.openBtn': 'Lichtshow öffnen',

    'settings.audio.title': 'Audioeinstellungen',

    'settings.bike.title': 'Fahrradfahren-Modus',
    'settings.bike.hint': 'Bei nur einem Ohrstöpsel: Ist eine Stimme (z. B. Bass) hart auf eine Seite gemischt, hört man sie sonst je nach Ohr gar nicht.',
    'settings.bike.normal': 'Normal',
    'settings.bike.mono': 'Mono',
    'settings.bike.swap': 'Tauschen',
    'settings.normalization.label': 'Lautstärke normalisieren',
    'settings.normalization.aria': 'Lautstärke normalisieren',
    'settings.normalization.hint': 'Gleicht Lautstärkeunterschiede zwischen Aufnahmen aus.',
    'settings.normalization.confirmTitle': 'Lautstärke normalisieren?',
    'settings.normalization.confirmText': 'Jede Aufnahme wird einmal auf diesem Gerät analysiert und das Ergebnis gespeichert. Die Analyse pausiert bei Wiedergabe, Aufnahme oder Import. Sehr lange oder große Aufnahmen werden übersprungen. Originaldateien bleiben unverändert.',
    'settings.normalization.activate': 'Aktivieren',
    'settings.normalization.cancel': 'Abbrechen',
    'settings.normalization.progress': 'Analyse: {done} von {total} Aufnahmen bearbeitet',
    'settings.normalization.counts': '{analyzed} von {total} erfolgreich, {failed} Fehler',
    'settings.normalization.retry': 'Erneut versuchen',
    'settings.normalization.clearAll': 'Neu analysieren',
    'settings.normalization.clearAllConfirmTitle': 'Alle Analyseergebnisse löschen?',
    'settings.normalization.clearAllConfirmText': 'Löscht alle gespeicherten Normalisierungsergebnisse (analysiert, übersprungen, fehlgeschlagen) für alle Songs auf diesem Gerät. Nützlich zum Ausprobieren — ist die Normalisierung noch aktiviert, wird danach alles neu analysiert. Originaldateien bleiben unberührt.',
    'settings.normalization.clearAllConfirm': 'Löschen',
    'settings.normalization.filter.all': 'Alle',
    'settings.normalization.filter.analyzed': 'Erledigt',
    'settings.normalization.filter.problems': 'Fehler',
    'settings.normalization.details.emptyFilter': 'Keine Einträge für diesen Filter.',
    'settings.normalization.reason.duration': 'Übersprungen: länger als 10 Minuten.',
    'settings.normalization.reason.compressed': 'Übersprungen: komprimierte Datei über 60 MiB.',
    'settings.normalization.reason.pcm': 'Übersprungen: geschätztes PCM über 128 MiB.',
    'settings.normalization.reason.metadataInvalid': 'Übersprungen: Samplerate oder Kanalanzahl unklar.',
    'settings.normalization.reason.durationInvalid': 'Übersprungen: Dauer unklar.',
    'settings.normalization.reason.metadataTimeout': 'Übersprungen: Zeitüberschreitung beim Metadatenlesen.',
    'settings.normalization.reason.decoderUnsupported': 'Übersprungen: Offline-Audioanalyse nicht unterstützt.',
    'settings.normalization.reason.decodeError': 'Fehlgeschlagen: Dekodierung fehlgeschlagen.',
    'settings.normalization.reason.storageError': 'Fehlgeschlagen: Datenbankfehler.',
    'settings.normalization.reason.crashGuard': 'Fehlgeschlagen: unterbrochen (App geschlossen?).',
    'settings.normalization.reason.unknown': 'Fehlgeschlagen: Ursache unbekannt.',
    'settings.normalization.unavailable': 'Normalisierung ist in diesem Wiedergabemodus nicht verfügbar.',
    'settings.normalization.paused.playback': 'Pausiert: läuft weiter, sobald Wiedergabe/Vorschau beendet ist.',
    'settings.normalization.paused.recording': 'Pausiert: läuft weiter, sobald die Aufnahme beendet ist.',
    'settings.normalization.paused.import': 'Pausiert: läuft weiter, sobald der Import abgeschlossen ist.',
    'settings.normalization.details.title': 'Analyseergebnisse je Datei',
    'settings.normalization.details.retryFile': 'Diese Datei erneut versuchen',
    'settings.normalization.details.showAll': 'Alle {count} anzeigen',
    'settings.normalization.details.technical': 'Technische Details',
    'settings.normalization.detail.minutes': '{time} Minuten',
    'settings.normalization.detail.fileInfo': '{duration} · {channels} · {rate}',
    'settings.normalization.detail.analyzed': 'Decode {decodeS} s · Analyse {analysisS} s · PCM {pcmMiB} MiB',
    'settings.normalization.detail.analyzedHint': 'Geschätzter PCM-Speicher des dekodierten Analyse-Audiopuffers — nicht der gesamte Browser-/Tab-Speicher.',
    'settings.normalization.detail.duration': 'Übersprungen: Die Aufnahme dauert {duration}. Erlaubt sind höchstens {limit}.',
    'settings.normalization.detail.compressed': 'Übersprungen: Die Datei ist {sizeMiB} MiB groß. Erlaubt sind höchstens {limitMiB} MiB.',
    'settings.normalization.detail.pcm': 'Übersprungen: Der geschätzte Audiospeicher beträgt {estimatedMiB} MiB. Erlaubt sind {limitMiB} MiB.',
    'settings.normalization.detail.metadataInvalid': 'Übersprungen: Samplerate oder Kanalanzahl konnten nicht zuverlässig ermittelt werden.',
    'settings.normalization.detail.durationInvalid': 'Übersprungen: Die Dauer der Aufnahme konnte nicht zuverlässig ermittelt werden.',
    'settings.normalization.detail.metadataTimeout': 'Übersprungen: Das Lesen der Metadaten hat zu lange gedauert.',
    'settings.normalization.detail.decoderUnsupported': 'Übersprungen: Dieser Browser unterstützt die Offline-Audioanalyse nicht.',
    'settings.normalization.detail.decodeError': 'Fehlgeschlagen: Der Browser konnte die Audiodatei nicht dekodieren. Das Format wird möglicherweise nicht unterstützt oder die Datei ist beschädigt.',
    'settings.normalization.detail.storageError': 'Fehlgeschlagen: Beim Zugriff auf die Datenbank ist ein Fehler aufgetreten.',
    'settings.normalization.detail.crashGuard': 'Fehlgeschlagen: Die Analyse wurde unterbrochen, bevor sie sicher abgeschlossen werden konnte — möglicherweise durch Schließen der App.',
    'settings.normalization.detail.unknown': 'Fehlgeschlagen: Die genaue Ursache konnte nicht ermittelt werden.',
    'settings.normalization.channels.mono': 'Mono',
    'settings.normalization.channels.stereo': 'Stereo',
    'settings.normalization.channels.multi': '{count} Kanäle',
    'settings.normalization.crashGuard.message': 'Die letzte Analyse von „{fileName}“ wurde unerwartet unterbrochen. Die automatische Analyse wurde vorsorglich pausiert.',
    'settings.normalization.crashGuard.resume': 'Fortsetzen',

    'settings.screen.title': 'Bildschirm & Hintergrund',
    'settings.screen.keepOn': 'Bildschirm anlassen, solange ein Lied geöffnet ist',
    'settings.screen.keepOnAria': 'Bildschirm anlassen',
    'settings.screen.hint': 'Verhindert nur das automatische Abdunkeln bei Untätigkeit — hilft nicht, wenn du das Handy bewusst über die Ein/Aus-Taste sperrst.',
    'settings.screen.bgHelpToggle': 'Hören im Hintergrund klappt nicht?',
    'settings.screen.bgHelpIntro': 'Bricht die Wiedergabe ab, sobald du das Handy sperrst, liegt das nicht an dieser App: Android entscheidet, ob eine Web-App im Hintergrund weiterlaufen darf, und das steuern zwei Systemeinstellungen — beide lassen sich nur von Hand ändern, keine Website darf sie selbst setzen.',
    'settings.screen.step1': 'Android-Einstellungen → <strong>Apps</strong> → deinen Browser öffnen (z. B. <strong>Vanadium</strong> oder <strong>Chrome</strong> — die App, in der du „Zum Startbildschirm hinzufügen" verwendet hast).',
    'settings.screen.step2': '<strong>Akku</strong> → <strong>Nicht eingeschränkt</strong> wählen. Sonst beendet Android den Browser im Hintergrund, sobald der Bildschirm aus ist.',
    'settings.screen.step3': '<strong>Benachrichtigungen</strong> → erlauben. Android verlangt dafür eine sichtbare Benachrichtigung — ohne sie darf keine Web-App im Hintergrund weiterspielen.',
    'settings.screen.grapheneNote': 'Ohne Google-Play-Dienste — etwa auf GrapheneOS — legt „Zum Startbildschirm hinzufügen" meist nur eine Verknüpfung an, kein eigenes App-Symbol mit eigenen Berechtigungen. Die beiden Einstellungen betreffen dann den Browser selbst, nicht ein eigenes „BVG"-Symbol.',
    'settings.screen.notifyBtn': 'Benachrichtigungen für diese Seite erlauben',

    'settings.perf.title': 'Kompatibilität & Performance',
    'settings.perf.modeHint': 'Wie das Verlangsamen bei 0,85×, 0,7× und 0,6× berechnet wird.',
    'settings.perf.modeStandard': 'Standard',
    'settings.perf.modeHd': 'HD',
    'settings.perf.hdHint': 'HD klingt bei langsamem Tempo klarer, braucht aber mehr Leistung. Bei Ruckeln oder Wärme: Standard wählen.',
    'settings.perf.hdUnsupported': 'Dieses Gerät unterstützt HD nicht — Standard funktioniert trotzdem.',
    'settings.perf.webkitHint': 'Safari kann langsames Audio noch fehlerhaft wiedergeben. Deshalb ist HD dort vorerst aus; mit „Trotzdem versuchen“ lässt es sich testen.',
    'settings.perf.webkitForceGraph': 'Trotzdem versuchen',
    'settings.perf.webkitForceGraphAria': 'Kanal-Matrix und HD trotz bekanntem Safari-Fehler erzwingen',
    'settings.perf.webkitForceGraphHint': 'Klingt es abgehackt oder mit falscher Tonhöhe, war der Fehler noch nicht behoben — dann hier wieder ausschalten.',
    'settings.perf.introTitle': 'HD-Modus',
    'settings.perf.introText': 'Im HD-Modus wird die Soundqualität beim langsamen Abspielen erhöht, was aber gerade auf alten Handys zur Überforderung führen kann. Kann unter Einstellungen rückgängig gemacht werden. Jetzt ausprobieren?',
    'settings.perf.introActivate': 'Ja, ausprobieren',
    'settings.perf.introStay': 'Nein danke',
    'settings.perf.rtLabel': 'Wiedergabetempo:',
    'settings.perf.rtSuffix': 'der Echtzeit',
    'settings.perf.rebuildBtn': 'Tonausgabe neu aufbauen',
    'settings.perf.rebuildHint': 'Bei Audioproblemen probieren.',
    'settings.perf.rebuildDone': 'Tonausgabe neu aufgebaut.',
    'rec.input.narrowband': 'Das Mikrofon läuft in Telefonqualität — typisch für Bluetooth-Kopfhörer, die beim Aufnehmen aufs Freisprechprofil umschalten. Dann klingt auch der Song dumpf. Kabelgebundene Kopfhörer oder Bluetooth aus helfen.',
    'rec.input.bluetooth': 'Aufnahme über ein Bluetooth-Headset. Viele Kopfhörer schalten dabei auf Telefonqualität um — auch für die Wiedergabe. Kabelgebundene Kopfhörer klingen deutlich besser.',
    'rec.input.bluetoothAfterUse': 'Android ist eventuell im Bluetooth-Freisprechprofil geblieben. Trenne Bluetooth beziehungsweise den Kopfhörer und verbinde ihn neu. „Tonausgabe neu aufbauen“ erneuert nur den Web-Audio-Graphen und kann das Android-Bluetoothprofil nicht zurücksetzen.',
    'settings.perf.advToggle': 'Erweitert: Zeitdehner einstellen',
    'settings.perf.advIntro': 'Wirkt sofort, auch während der Wiedergabe. Zum Ausprobieren gedacht — die Voreinstellungen sind bewusst so gewählt, wie sie sind.',
    'settings.perf.advGroupSound': 'Klang',
    'settings.perf.advGroupCost': 'Rechenaufwand',
    'settings.perf.advFormantComp': 'Formantkorrektur',
    'settings.perf.advFormantCompHint': 'Sollte hier aus bleiben: das Resampling zieht Tonhöhe und Formanten gemeinsam nach unten, das Hochschieben holt beide gemeinsam zurück. Eingeschaltet klingt es dunkler, nicht besser.',
    'settings.perf.advFormantSemi': 'Formanten verschieben',
    'settings.perf.advFormantBase': 'Formant-Grundton',
    'settings.perf.advFormantBaseAuto': 'automatisch',
    'settings.perf.advTonality': 'Grenze für Tonhaftigkeit',
    'settings.perf.advPresetDefault': 'Standard',
    'settings.perf.advPresetCheap': 'Sparsam',
    'settings.perf.advBlock': 'Blocklänge',
    'settings.perf.advBlockAuto': 'nach Voreinstellung',
    'settings.perf.advInterval': 'Schrittweite',
    'settings.perf.advIntervalAuto': 'automatisch',
    'settings.perf.advSplit': 'Rechnung über die Quanten verteilen',
    'settings.perf.advSplitHint': 'Verteilt die Arbeit eines Analyseblocks über mehrere Render-Quanten. Kostet gemessen keine Rechenzeit, nur ein Viertel mehr Latenz — deshalb ab Werk an. Ausschalten macht die Wiedergabe direkter, aber stoßweiser.',
    'settings.perf.advLatency': 'Latenz des Zeitdehners:',
    'settings.perf.advSemitones': 'Tonhöhenkorrektur:',
    'settings.perf.advReset': 'Zurücksetzen',
    'settings.perf.advUnitSemi': 'Halbtöne',
    'settings.perf.advIsDefault': 'ab Werk',
    'settings.perf.advIsDefaultSuffix': ' · ab Werk',
    'settings.perf.advPresetIsDefault': 'Preset steht auf Voreinstellung',
    'settings.perf.advUnitLatency': 'Latenz',
    'settings.perf.advSplitInactive': 'Wirkungslos, solange ein Preset gewählt ist: die Bibliothek bestimmt dort Blocklänge und Schrittweite selbst. Eine eigene Blocklänge einstellen, dann greift der Schalter.',
    'settings.perf.advCostHint': 'Wirklich sparsamer wird es nur über die Schrittweite oder das Preset „Sparsam": eine größere Schrittweite heißt weniger Analyseblöcke je Sekunde. Die Blocklänge dagegen ändert am Rechenaufwand fast nichts, sie bestimmt Frequenzauflösung und Latenz.',
    'settings.perf.advAb': 'A/B',
    'settings.perf.advAbAria': 'Standard und eigene Einstellungen vergleichen',
    'settings.perf.advAbHint': 'Du hörst gerade die Voreinstellung zum Vergleich — deine eigenen Werte sind unverändert gespeichert.',
    'settings.perf.advCopy': 'Kopieren',
    'settings.perf.advCopied': 'Einstellungen in die Zwischenablage kopiert.',
    'settings.perf.advOn': 'an',
    'settings.perf.advOff': 'aus',

    'settings.help.title': 'Hilfe',
    'settings.help.intro': 'Die Aufnahmen kommen als ZIP-Datei aus der Dropbox in die App. Der Knopf unten zeigt Schritt für Schritt, wie das auf dem iPhone und auf Android geht.',
    'settings.help.howToBtn': 'Wie bekomme ich Songs in die App?',
    'settings.help.replayOnboarding': 'Einführung noch einmal ansehen',

    'settings.data.title': 'Daten & Sicherung',
    'settings.data.backupTitle': 'Sicherung',
    'settings.data.backupBtn': 'Backup',
    'settings.data.restoreBtn': 'Restore',
    'settings.data.printNotesBtn': 'Notizen',
    'settings.data.printLyricsBtn': 'Eigene Liedtexte',
    'settings.data.importNotesBtn': 'Notizen importieren',
    'settings.data.importLyricsBtn': 'Liedtexte importieren',
    'settings.data.importNotesLabel': 'Notizen',
    'settings.data.importLyricsLabel': 'Liedtexte',
    'settings.data.importConfirmTitle': 'Datei importieren?',
    'settings.data.importConfirmText': '{count} {label} werden importiert. Bereits vorhandene Einträge derselben Songs werden ersetzt.',
    'settings.data.importAction': 'Importieren',
    'settings.data.importDone': '{count} {label} importiert.',
    'settings.data.importWrongKind': 'Diese Datei enthält die andere Textart.',
    'settings.data.importInvalid': 'Die Datei hat nicht das erwartete Chor-App-Exportformat.',
    'settings.data.exportTitle': 'Exportieren',
    'settings.data.manageTitle': 'Songs verwalten',
    'settings.data.dropAudioBtn': 'Nur Aufnahmen löschen',
    'settings.data.manageStorageBtn': 'Einzelne Songs verwalten',
    'settings.data.renameSongTitle': 'Song umbenennen',
    'settings.data.renameSongPlaceholder': 'Songtitel',
    'settings.data.renameSongAction': 'Umbenennen',
    'settings.data.renameSongExists': 'Ein Song mit diesem Titel ist bereits vorhanden.',
    'settings.data.renameSongDone': 'Song umbenannt.',
    'settings.data.deleteTitle': 'Löschen',
    'settings.data.deleteHint': 'Beides lässt sich nicht rückgängig machen; die Dateien in der Dropbox bleiben in jedem Fall unberührt. „Nur Aufnahmen löschen" entfernt nur die Audiodateien — Loops, Notizen, eigene Liedtexte und Setlisten bleiben erhalten und verbinden sich beim nächsten Import neu. „Alles löschen" entfernt zusätzlich auch diese.',
    'settings.data.wipeBtn': 'Alles löschen',

    'settings.about.title': 'Über die App',
    'settings.about.version': 'Version',
    'settings.about.offline': 'Offline verfügbar',
    'settings.about.checkUpdate': 'prüfen',
    'settings.about.checkingUpdate': 'Suche nach einer neueren Version …',
    'settings.about.upToDate': 'Du hast bereits die aktuelle Version.',
    'settings.about.checkUpdateFailed': 'Die Suche nach einer neueren Version ist fehlgeschlagen.',
    'settings.about.checkUpdateUnsupported': 'Aktualisierungen lassen sich in diesem Browser nicht manuell prüfen.',
    'settings.about.forceUpdate': 'sofort aktualisieren',
    'settings.about.forcingUpdate': 'Suche nach einer neueren Version — wird bei Fund sofort geladen …',
    'settings.about.forceUpdateApplying': 'Neuere Version gefunden, wird geladen …',
    'settings.about.privacy': 'Die App selbst stellt keine automatischen Netzwerkanfragen und sendet keine Daten — alles bleibt auf diesem Gerät. Nutzt man die optionale Liedsuche (Lupe im Player), gehen Songtitel und ggf. Interpret an den dort gewählten externen Dienst (Tidal, Spotify, Deezer, YouTube oder Google).',
    'settings.about.librariesTitle': 'Verwendete externe Bibliotheken:',
    'settings.about.lame': 'MP3-Export mit <strong>lamejs</strong> (LGPL-3.0), basierend auf <strong>LAME</strong> — <a href="https://lame.sourceforge.net/" target="_blank" rel="noopener noreferrer">lame.sourceforge.net</a>.',
    'settings.about.stretch': 'Verlangsamung im Modus „HD" mit <strong>signalsmith-stretch</strong> (MIT) von Geraint Luff / Signalsmith Audio Ltd. — <a href="https://signalsmith-audio.co.uk/code/stretch/" target="_blank" rel="noopener noreferrer">signalsmith-audio.co.uk</a>.',
    'settings.about.errorLogTitle': 'Fehlerprotokoll',
    'settings.about.errorLogHint': 'Technische Fehlermeldungen der App, neueste zuerst — hilfreich beim Melden eines Problems. Bleibt nur auf diesem Gerät.',
    'settings.about.errorLogEmpty': 'Keine Fehler aufgezeichnet.',
    'settings.about.copyLogBtn': 'Protokoll kopieren',
    'settings.about.clearBtn': 'Leeren',
    'settings.about.debugLogTitle': 'Diagnose-Log',
    'settings.about.debugLogSwitch': 'Ausführliches Protokoll für schwer fassbare Fehler aufzeichnen',
    'settings.about.debugLogAria': 'Diagnose-Log aufzeichnen',
    'settings.about.debugLogHint': 'Zeichnet technische Abläufe auf (Zeitstempel, Zustände, Zahlen) — nie Songtitel, Dateinamen oder Namen. Sinnvoll direkt vor dem Nachstellen eines Problems (z. B. Import, dann Bildschirm sperren); danach hier exportieren und beim Melden mitschicken.',
    'settings.about.exportLogBtn': 'Log exportieren',

    'settings.storage.title': 'Speicher',
    'settings.storage.measuring': 'wird ermittelt …',
    'settings.storage.persistBtn': 'Dauerhafte Speicherung anfordern',

    'onb.step1of5': 'Schritt 1 von 2',
    'onb.step2of5': 'Schritt 2 von 5',
    'onb.step3of5': 'Schritt 2 von 2',
    'onb.step4of5': 'Schritt 4 von 5',
    'onb.step5of5': 'Schritt 5 von 5',
    'onb.skip': 'Überspringen',
    'onb.back': 'Zurück',
    'onb.next': 'Weiter',

    'onb.slide1.title': 'Auf den Home&#8209;Bildschirm legen',
    'onb.slide1.text': 'So startet die App wie jede andere: eigenes Symbol, kein Browserfenster, volle Bildschirmhöhe. Vor allem aber behält das System die Aufnahmen länger, wenn die App installiert ist.',

    'onb.slide2.title': 'Welche Stimme singst du?',
    'onb.slide2.text': 'Zu jedem Lied gibt es mehrere Aufnahmen — eine je Stimme und eine Gesamtmischung. Mit deiner Stimme weiß die App zweierlei:',
    'onb.slide2.li1': '<strong>Beim Import</strong> sind deine Stimme und die Gesamtmischung vorausgewählt — der Rest bleibt draußen und spart Speicherplatz.',
    'onb.slide2.li2': '<strong>Im Player</strong> klingt gleich deine Stimme, ohne dass du sie bei jedem Lied neu einstellst.',
    'onb.slide2.footnote': 'Alle Stimmen bleiben trotzdem wählbar. Änderbar unter <strong>Einstellungen&nbsp;→&nbsp;Meine Stimmen</strong>.',

    'onb.slide3.title': 'Aufnahmen dauerhaft behalten',
    'onb.slide3.text1': 'Bei knappem Speicher darf das System die Daten einer Web-App löschen.',
    'onb.slide3.text2': 'Mit einem Klick bitten wir darum, die Aufnahmen <strong>dauerhaft</strong> zu behalten.',

    'onb.slide4.title': 'Die schwere Stelle üben',
    'onb.slide4.intro': '<strong>Abschnitt wiederholen.</strong> Im Player unter „Abschnitt üben":',
    'onb.slide4.li1': 'An der Stelle, wo es losgehen soll, auf <strong>A</strong> tippen.',
    'onb.slide4.li2': 'Am Ende der Stelle auf <strong>B</strong> tippen.',
    'onb.slide4.li3': 'Den <strong>Schalter</strong> daneben einschalten — der Abschnitt läuft jetzt in der Schleife, bis du ihn kannst.',
    'onb.slide4.li4': 'Über das <strong>Disketten-Symbol</strong> lässt sich der Abschnitt benennen und bleibt gespeichert, auch nach dem Schließen.',
    'onb.slide4.speed': '<strong>Langsamer üben.</strong> Unten rechts im Player steht die Geschwindigkeit: <strong>1,0×</strong>, <strong>0,85×</strong>, <strong>0,7×</strong> oder <strong>0,6×</strong>. Die Tonhöhe bleibt dabei gleich — es klingt langsamer, nicht tiefer. Beides zusammen ist der Kern der App: einen kurzen Abschnitt so lange langsam wiederholen, bis er sitzt.',

    'onb.slide5.title': 'Songs holen, Programm planen',
    'onb.slide5.import': '<strong>Import.</strong> Die Aufnahmen liegen im geteilten Dropbox-Ordner. Öffne ihn dafür im <strong>Browser</strong> — nicht in der Dropbox-App, die kann Ordner nicht als ZIP herunterladen —, lade ihn einmal als <strong>ZIP-Datei</strong> herunter und wählst sie unter „Einstellungen → Songs importieren" aus. Vor dem Speichern zeigt die App, was sie gefunden hat, und du hakst ab, welche Stimmen wirklich aufs Handy sollen. Jeder weitere Import <strong>ergänzt</strong> nur — Vorhandenes bleibt, fehlende Stimmen lassen sich nachladen.',
    'onb.slide5.setlists': '<strong>Setlisten.</strong> Eine Setliste ist ein Programm: die Lieder in der Reihenfolge, in der sie gesungen werden. Am Ende eines Liedes schaltet die App von selbst weiter. Der Chorleiter kann eine Setliste als schlichte Textdatei verteilen — ein Titel je Zeile —, du spielst sie unter „Setlisten" ein.',
    'onb.slide5.note': 'Alles bleibt auf diesem Gerät. Die App sendet nichts und braucht nach dem Import kein Internet mehr.',

    'common.cancel': 'Abbrechen',
    'common.close': 'Schließen',

    'import.backAria': 'Zurück zu den Einstellungen',
    'import.intro': 'Die Aufnahmen liegen im geteilten Dropbox-Ordner. Öffne Dropbox dafür im <strong>Browser</strong> (nicht in der Dropbox-App — die kann Ordner nicht als ZIP herunterladen), lade den Ordner einmal als ZIP-Datei herunter und wählst sie hier aus. Danach ist alles offline auf dem Handy — ohne Dropbox, ohne Internet.',
    'import.pickZipBtn': 'ZIP-Datei auswählen',
    'import.pickFolderBtn': 'Stattdessen einen Ordner wählen',
    'import.desktopOnly': 'Nur am Computer verfügbar.',
    'import.goodToKnowTitle': 'Gut zu wissen',
    'import.goodToKnow1': 'Jeder Import <strong>ergänzt</strong> die Bibliothek. Bereits vorhandene Songs bleiben erhalten.',
    'import.goodToKnow2': 'Du kannst später einzelne Lieder oder fehlende Stimmen nachladen.',
    'import.goodToKnow3': 'Vor dem Speichern kannst du auswählen, welche Stimmen aufs Handy sollen — das spart Speicherplatz.',
    'import.goodToKnow4': 'Die heruntergeladene ZIP-Datei lässt sich danach gefahrlos löschen — alles Nötige ist jetzt auf dem Gerät.',
    'import.libraryTitle': 'Bibliothek',
    'import.libSongs': 'Songs',
    'import.libFiles': 'Dateien',
    'import.libLastImport': 'Letzter Import',
    'import.sheetTitle': 'Auswahl',
    'import.presetMine': 'Meine Stimmen',
    'import.presetFull': 'Full',
    'import.presetAll': 'Alle Stimmen',
    'import.importBtn': 'Importieren',
    'import.attachSimilarPrefix': 'Loops, Notizen und Liedtext von',
    'import.attachSimilarSuffix': 'übernehmen',

    'songs.searchPlaceholder': 'Song suchen …',
    'songs.searchAria': 'Song suchen',
    'songs.feelingLuckyAria': 'Feeling Lucky — zufälliges Lied abspielen',
    'songs.recordAria': 'Aufnehmen',

    'playlists.searchPlaceholder': 'Song suchen oder Platzhalter hinzufügen …',
    'playlists.searchAria': 'Song für die Setliste suchen',
    'playlists.emptyTitle': 'Noch keine Setlisten',
    'playlists.emptyText': 'Lege eine an oder importiere die Textdatei des Chorleiters.',

    'songs.emptyTitle': 'Noch keine Songs',
    'songs.emptyText': 'Lade die Aufnahmen aus der Dropbox als ZIP-Datei herunter und importiere sie hier.',
    'songs.notFoundTitle': 'Nichts gefunden',
    'songs.notFoundText': 'Kein Song passt zu dieser Suche.',
    'songs.createPlaceholderSuffix': 'als Platzhalter anlegen',
    'songs.createPlaceholderHint': 'Noch nicht importiertes Lied anlegen — für Liedtext, Notizen oder eine Setliste.',
    'songs.placeholderBadge': 'noch keine Aufnahme',
    'songs.setlistMissingBadge': 'nicht in der Bibliothek',
    'player.placeholderHint': 'Noch keine Aufnahme importiert. Liedtext und Notizen kannst du trotzdem schon speichern — sie verbinden sich automatisch beim nächsten Import.',
    'player.hdStarve': 'HD kam im Hintergrund nicht mit: bei ausgeschaltetem Bildschirm drosselt dieses Gerät die Rechenleistung, und der HD-Zeitdehner schafft die Verlangsamung dann nicht mehr in Echtzeit. Daher das Stottern.',
    'player.hdStarveAction': 'Auf Standard umstellen',

    'lightshow.backAria': 'Zurück zu den Einstellungen',
    'lightshow.noVoiceHint': 'Noch keine Stimme gewählt — die Show verwendet vorerst den Sopran-Block. Ändern unter <strong>Einstellungen → Meine Stimmen</strong>, oder hier nur für die Show festlegen:',
    'lightshow.voicePickerAria': 'Stimme für die Lichtshow',
    'lightshow.voicePrefix': 'Du leuchtest als',
    'lightshow.showsTitle': 'Show wählen',
    'lightshow.startBtn': 'Show starten',
    'lightshow.rehearsalLabel': 'Probelauf — startet sofort, ohne auf den Rasterpunkt zu warten',
    'lightshow.rehearsalAria': 'Probelauf',
    'lightshow.rehearsalHint': 'Steht nach dem Schließen dieser Ansicht wieder aus — sonst steht jemand auf der Bühne im Probelauf.',
    'lightshow.syncTitle': 'Zeit synchronisieren',
    'lightshow.syncInfo': 'Ganz am Anfang einmal die Uhr dieses Handys mit dem PTB-Zeitserver abgleichen. Die ermittelte Korrektur gilt danach für Vorschauen und Shows.',
    'lightshow.syncBtn': 'Mit Serverzeit synchronisieren',
    'lightshow.previewBtn': 'Vorschau abspielen',
    'lightshow.hintBlock': 'Bildschirmhelligkeit vor dem Auftritt von Hand hochdrehen — das kann die App nicht selbst tun. Handy während der Show nicht sperren und oben vor dem Start einmal mit der Serverzeit synchronisieren.',
    'lightshow.seizureWarning': 'Die Shows arbeiten mit hellen, wechselnden Flächen. Wer lichtempfindlich ist oder zu Anfällen neigt, macht besser nicht mit oder wählt „Sternenmeer".',
    'lightshow.reducedMotionHint': 'Dieses Gerät bevorzugt weniger Bewegung — „Sternenmeer" ist deshalb vorausgewählt. Die anderen Shows lassen sich trotzdem starten.',
    'lightshow.recommendedBadge': 'Empfohlen',

    'lightshow.show.sterne.name': 'Sternenmeer',
    'lightshow.show.sterne.desc': 'Eine gemeinsame tiefe Nachtfläche, in der ruhige farbige Sternbilder durch alle Stimmen wandern.',
    'lightshow.show.puls.name': 'Herzschlag',
    'lightshow.show.puls.desc': 'Der ganze Chor schlägt gemeinsam in Rot; farbige Echos und ein weißes Finale verdichten den Puls.',
    'lightshow.show.welle.name': 'Aurora',
    'lightshow.show.welle.desc': 'Alle Stimmen leuchten durchgehend, während ein heller Saum durch wechselnde Polarlichtfarben zieht.',
    'lightshow.show.finale.name': 'Finale',
    'lightshow.show.finale.desc': 'Große gemeinsame Flächen, symmetrische Akzente und kräftige Weißschnitte bauen sich zum Höhepunkt auf.',
    'lightshow.show.prisma.name': 'Prisma',
    'lightshow.show.prisma.desc': 'Farbakkorde drehen und spiegeln sich, bevor der ganze Chor in gemeinsamen Neonflächen zusammenfindet.',
    'lightshow.show.domino.name': 'Domino',
    'lightshow.show.domino.desc': 'Ein voller Farbteppich bleibt stehen, während helle Akzente hindurchlaufen und in Tutti-Flächen münden.',
    'lightshow.show.dialog.name': 'Dialog',
    'lightshow.show.dialog.desc': 'Gemeinsame Aussagen wechseln mit Antworten der Bühnenhälften, Außenstimmen und Innenstimmen.',
    'lightshow.show.kaleidoskop.name': 'Kaleidoskop',
    'lightshow.show.kaleidoskop.desc': 'Schnelle symmetrische Farbflächen setzen sich immer neu zusammen und werden regelmäßig zum Tutti.',

    'lightshow.syncLevel.unkritisch': 'verzeiht schiefe Uhren',
    'lightshow.syncLevel.hoch': 'verzeiht kleine Abweichungen',
    'lightshow.syncLevel.mittel': 'braucht einigermaßen gestellte Uhren',
    'lightshow.syncLevel.empfindlich': 'braucht gut gestellte Uhren',



    'lightshow.ntpcal.dialogTitle': 'Mit Internetzeit abgleichen?',
    'lightshow.ntpcal.dialogText': 'Dafür schickt die App eine einmalige Anfrage an die Atomuhr der PTB (Physikalisch-Technische Bundesanstalt, uhr.ptb.de), um die aktuelle Uhrzeit abzufragen. Es werden keine weiteren Daten übertragen — nur diese eine Zeitabfrage.',
    'lightshow.ntpcal.dialogOk': 'Abgleichen',
    'lightshow.ntpcal.dialogCancel': 'Abbrechen',
    'lightshow.ntpcal.statusChecking': 'Frage Zeitserver ab …',
    'lightshow.ntpcal.statusDone': 'Fertig — Zeitkorrektur auf {value} gesetzt (Laufzeit {rtt}, geschätzte Genauigkeit ±{uncertainty}).',
    'lightshow.ntpcal.statusClockError': 'Die Geräteuhr weicht um {value} ab. Bitte zuerst Datum und Uhrzeit des Geräts korrigieren.',
    'lightshow.ntpcal.statusError': 'Zeitserver nicht erreichbar — bitte später erneut versuchen.',
  },
  en: {
    'nav.songs': 'Songs',
    'nav.playlists': 'Setlists',
    'nav.player': 'Player',
    'nav.settings': 'Settings',

    'tabs.loops': 'Loops',
    'tabs.rec': 'REC',
    'tabs.lyrics': 'Lyrics',
    'tabs.notes': 'Notes',
    'scores.hintLabel': 'Scores available',
    'scores.modalTitle': 'Scores',

    'settings.importBtn': 'Import songs',
    'settings.personal.title': 'Make it yours!',
    'settings.personal.behaviorTitle': 'Behavior',
    'settings.personal.displayTitle': 'Display',
    'settings.personal.tabHint': 'Tab that shows first when you open a song.',
    'settings.personal.tabGroupAria': 'Default tab in the player',
    'settings.personal.language': 'Language',
    'settings.personal.accent': 'Accent color',
    'settings.personal.presentTitle': 'Text display for others',
    'settings.personal.presentHint': 'Color of the full-screen display for others to read along (fullscreen button in Lyrics).',
    'settings.personal.presentThemeDark': 'White on black',
    'settings.personal.presentThemeLight': 'Black on white',
    'settings.personal.searchTitle': 'Song search',
    'settings.personal.searchHint': 'Service used by the magnifying-glass icon in the player. Long-press it to pick a different service just once.',
    'settings.personal.searchPrivacyHint': 'Tapping the magnifying glass in the player sends the song title (and artist, if known) to the service selected here.',

    'songsearch.dialogTitle': 'External search',
    'songsearch.dialogPrefix': 'Opens ',
    'songsearch.dialogSuffix': ' and sends the song title there to search for it.',
    'songsearch.dialogServiceLabel': 'Service',
    'songsearch.dialogOk': 'Sounds good',
    'songsearch.dialogCancel': 'Not now',

    'settings.voices.title': 'My voices',
    'settings.voices.hint': 'Multiple selection possible, for anyone switching between voices. Determines which tracks are pre-selected on import and which voice the player shows first.',

    'settings.lightshow.title': 'Light show',
    'settings.lightshow.hint': 'Eight on-stage moments for the concert: full-screen colours stage each voice as a separate block and stay in sync via the system clock.',
    'settings.lightshow.openBtn': 'Open light show',

    'settings.audio.title': 'Audio settings',

    'settings.bike.title': 'Bicycle mode',
    'settings.bike.hint': 'With only one earbud in: if a voice (e.g. bass) is hard-panned to one side, you might not hear it at all depending on your ear.',
    'settings.bike.normal': 'Normal',
    'settings.bike.mono': 'Mono',
    'settings.bike.swap': 'Swap',
    'settings.normalization.label': 'Normalize volume',
    'settings.normalization.aria': 'Normalize volume',
    'settings.normalization.hint': 'Balances volume differences between recordings.',
    'settings.normalization.confirmTitle': 'Normalize volume?',
    'settings.normalization.confirmText': 'Each recording is analyzed once on this device and the result is saved. Analysis pauses during playback, recording, or import. Very long or large recordings are skipped. Original files stay unchanged.',
    'settings.normalization.activate': 'Activate',
    'settings.normalization.cancel': 'Cancel',
    'settings.normalization.progress': 'Analysis: {done} of {total} recordings processed',
    'settings.normalization.counts': '{analyzed} of {total} successful, {failed} errors',
    'settings.normalization.retry': 'Retry',
    'settings.normalization.clearAll': 'Reanalyze',
    'settings.normalization.clearAllConfirmTitle': 'Clear all analysis results?',
    'settings.normalization.clearAllConfirmText': 'Deletes every saved normalization result (analyzed, skipped, failed) for every song on this device. Useful for experimenting — if normalization is still enabled, everything is analyzed again afterward. Original files are untouched.',
    'settings.normalization.clearAllConfirm': 'Clear',
    'settings.normalization.filter.all': 'All',
    'settings.normalization.filter.analyzed': 'Done',
    'settings.normalization.filter.problems': 'Errors',
    'settings.normalization.details.emptyFilter': 'No entries for this filter.',
    'settings.normalization.reason.duration': 'Skipped: longer than 10 minutes.',
    'settings.normalization.reason.compressed': 'Skipped: compressed file exceeds 60 MiB.',
    'settings.normalization.reason.pcm': 'Skipped: estimated PCM exceeds 128 MiB.',
    'settings.normalization.reason.metadataInvalid': 'Skipped: sample rate or channel count unclear.',
    'settings.normalization.reason.durationInvalid': 'Skipped: duration unclear.',
    'settings.normalization.reason.metadataTimeout': 'Skipped: timed out reading metadata.',
    'settings.normalization.reason.decoderUnsupported': 'Skipped: offline audio analysis not supported.',
    'settings.normalization.reason.decodeError': 'Failed: decoding failed.',
    'settings.normalization.reason.storageError': 'Failed: database error.',
    'settings.normalization.reason.crashGuard': 'Failed: interrupted (app closed?).',
    'settings.normalization.reason.unknown': 'Failed: cause unknown.',
    'settings.normalization.unavailable': 'Normalisation is not available in this playback mode.',
    'settings.normalization.paused.playback': 'Paused: resumes once playback/preview ends.',
    'settings.normalization.paused.recording': 'Paused: resumes once recording ends.',
    'settings.normalization.paused.import': 'Paused: resumes once the import finishes.',
    'settings.normalization.details.title': 'Per-file analysis results',
    'settings.normalization.details.retryFile': 'Retry this file',
    'settings.normalization.details.showAll': 'Show all {count}',
    'settings.normalization.details.technical': 'Technical details',
    'settings.normalization.detail.minutes': '{time} minutes',
    'settings.normalization.detail.fileInfo': '{duration} · {channels} · {rate}',
    'settings.normalization.detail.analyzed': 'Decode {decodeS} s · Analysis {analysisS} s · PCM {pcmMiB} MiB',
    'settings.normalization.detail.analyzedHint': 'Estimated PCM memory of the decoded analysis audio buffer — not total browser/tab memory.',
    'settings.normalization.detail.duration': 'Skipped: the recording is {duration} long. Allowed is at most {limit}.',
    'settings.normalization.detail.compressed': 'Skipped: the file is {sizeMiB} MiB. Allowed is at most {limitMiB} MiB.',
    'settings.normalization.detail.pcm': 'Skipped: estimated audio memory is {estimatedMiB} MiB. Allowed is {limitMiB} MiB.',
    'settings.normalization.detail.metadataInvalid': 'Skipped: sample rate or channel count could not be reliably determined.',
    'settings.normalization.detail.durationInvalid': 'Skipped: the recording’s duration could not be reliably determined.',
    'settings.normalization.detail.metadataTimeout': 'Skipped: reading metadata took too long.',
    'settings.normalization.detail.decoderUnsupported': 'Skipped: this browser does not support offline audio analysis.',
    'settings.normalization.detail.decodeError': 'Failed: the browser could not decode the audio file. The format may be unsupported, or the file may be corrupt.',
    'settings.normalization.detail.storageError': 'Failed: an error occurred accessing the database.',
    'settings.normalization.detail.crashGuard': 'Failed: analysis was interrupted before it could finish safely — possibly by closing the app.',
    'settings.normalization.detail.unknown': 'Failed: the exact cause could not be determined.',
    'settings.normalization.channels.mono': 'Mono',
    'settings.normalization.channels.stereo': 'Stereo',
    'settings.normalization.channels.multi': '{count} channels',
    'settings.normalization.crashGuard.message': 'The last analysis of “{fileName}” was interrupted unexpectedly. Automatic analysis has been paused as a precaution.',
    'settings.normalization.crashGuard.resume': 'Resume',

    'settings.screen.title': 'Screen & background',
    'settings.screen.keepOn': 'Keep the screen on while a song is open',
    'settings.screen.keepOnAria': 'Keep screen on',
    'settings.screen.hint': 'Only prevents automatic dimming from inactivity — doesn\'t help if you lock the phone yourself with the power button.',
    'settings.screen.bgHelpToggle': 'Background playback not working?',
    'settings.screen.bgHelpIntro': 'If playback stops as soon as you lock your phone, that\'s not this app\'s fault: Android decides whether a web app may keep running in the background, controlled by two system settings — both can only be changed by hand, no website can set them itself.',
    'settings.screen.step1': 'Android settings → <strong>Apps</strong> → open your browser (e.g. <strong>Vanadium</strong> or <strong>Chrome</strong> — the app you used "Add to home screen" with).',
    'settings.screen.step2': '<strong>Battery</strong> → choose <strong>Unrestricted</strong>. Otherwise Android shuts the browser down in the background as soon as the screen turns off.',
    'settings.screen.step3': '<strong>Notifications</strong> → allow. Android requires a visible notification for this — without it, no web app may keep playing in the background.',
    'settings.screen.grapheneNote': 'Without Google Play services — e.g. on GrapheneOS — "Add to home screen" usually only creates a shortcut, not a proper app icon with its own permissions. Both settings then apply to the browser itself, not a separate "BVG" icon.',
    'settings.screen.notifyBtn': 'Allow notifications for this page',

    'settings.perf.title': 'Compatibility & performance',
    'settings.perf.modeHint': 'How slowing down at 0.85×, 0.7× and 0.6× is computed.',
    'settings.perf.modeStandard': 'Standard',
    'settings.perf.modeHd': 'HD',
    'settings.perf.hdHint': 'HD sounds clearer at slower speeds but uses more power. If playback stutters or the phone gets warm, choose Standard.',
    'settings.perf.hdUnsupported': "This device doesn't support HD — Standard still works.",
    'settings.perf.webkitHint': 'Safari may still play slowed audio incorrectly. HD is therefore off there for now; use “Try anyway” to test it.',
    'settings.perf.webkitForceGraph': 'Try anyway',
    'settings.perf.webkitForceGraphAria': 'Force channel mode and HD despite the known Safari bug',
    'settings.perf.webkitForceGraphHint': "If it sounds choppy or the pitch is off, the bug isn't fixed yet — switch this back off.",
    'settings.perf.introTitle': 'HD mode',
    'settings.perf.introText': "HD mode increases sound quality during slow playback, but this can be too much for older phones to handle. Can be reversed under Settings. Try it now?",
    'settings.perf.introActivate': 'Yes, try it',
    'settings.perf.introStay': 'No thanks',
    'settings.perf.rtLabel': 'Playback speed:',
    'settings.perf.rtSuffix': 'of real time',
    'settings.perf.rebuildBtn': 'Rebuild audio output',
    'settings.perf.rebuildHint': 'Try this if you have audio problems.',
    'settings.perf.rebuildDone': 'Audio output rebuilt.',
    'rec.input.narrowband': 'The microphone is running at telephone quality, which is typical when Bluetooth headphones switch to hands-free mode for recording. The song will sound muffled too. Wired headphones or switching Bluetooth off will help.',
    'rec.input.bluetooth': 'Recording through a Bluetooth headset. Many headphones switch to telephone quality for this, including playback. Wired headphones sound considerably better.',
    'rec.input.bluetoothAfterUse': 'Android may have remained in Bluetooth hands-free mode. Disconnect and reconnect Bluetooth or the headphones. “Rebuild audio output” only rebuilds the Web Audio graph and cannot reset Android’s Bluetooth profile.',
    'settings.perf.advToggle': 'Advanced: tune the stretcher',
    'settings.perf.advIntro': 'Takes effect immediately, even during playback. Meant for experimenting — the defaults are chosen deliberately.',
    'settings.perf.advGroupSound': 'Sound',
    'settings.perf.advGroupCost': 'Processing cost',
    'settings.perf.advFormantComp': 'Formant correction',
    'settings.perf.advFormantCompHint': 'Should stay off here: the resampling pulls pitch and formants down together, and shifting back up brings both back together. Switched on it sounds darker, not better.',
    'settings.perf.advFormantSemi': 'Shift formants',
    'settings.perf.advFormantBase': 'Formant base note',
    'settings.perf.advFormantBaseAuto': 'automatic',
    'settings.perf.advTonality': 'Tonality limit',
    'settings.perf.advPresetDefault': 'Standard',
    'settings.perf.advPresetCheap': 'Cheaper',
    'settings.perf.advBlock': 'Block length',
    'settings.perf.advBlockAuto': 'from preset',
    'settings.perf.advInterval': 'Step size',
    'settings.perf.advIntervalAuto': 'automatic',
    'settings.perf.advSplit': 'Spread computation across quanta',
    'settings.perf.advSplitHint': 'Spreads one analysis block over several render quanta. Measured to cost no extra compute, only a quarter more latency — hence on by default. Turning it off is more immediate but burstier.',
    'settings.perf.advLatency': 'Stretcher latency:',
    'settings.perf.advSemitones': 'Pitch correction:',
    'settings.perf.advReset': 'Reset',
    'settings.perf.advUnitSemi': 'semitones',
    'settings.perf.advIsDefault': 'stock',
    'settings.perf.advIsDefaultSuffix': ' · stock',
    'settings.perf.advPresetIsDefault': 'Preset is at its default',
    'settings.perf.advUnitLatency': 'latency',
    'settings.perf.advSplitInactive': 'Has no effect while a preset is selected: there the library sets block length and step size itself. Set your own block length and the switch takes effect.',
    'settings.perf.advCostHint': 'Real savings come only from the step size or the "Cheaper" preset: a larger step means fewer analysis blocks per second. Block length barely changes the cost — it sets frequency resolution and latency.',
    'settings.perf.advAb': 'A/B',
    'settings.perf.advAbAria': 'Compare standard and your own settings',
    'settings.perf.advAbHint': "You're previewing the default for comparison — your own settings are unchanged and still saved.",
    'settings.perf.advCopy': 'Copy',
    'settings.perf.advCopied': 'Settings copied to clipboard.',
    'settings.perf.advOn': 'on',
    'settings.perf.advOff': 'off',

    'settings.help.title': 'Help',
    'settings.help.intro': 'Recordings come into the app as a ZIP file from Dropbox. The button below walks through it step by step for iPhone and Android.',
    'settings.help.howToBtn': 'How do I get songs into the app?',
    'settings.help.replayOnboarding': 'Watch the intro again',

    'settings.data.title': 'Data & backup',
    'settings.data.backupTitle': 'Backup',
    'settings.data.backupBtn': 'Backup',
    'settings.data.restoreBtn': 'Restore',
    'settings.data.printNotesBtn': 'Notes',
    'settings.data.printLyricsBtn': 'Your own lyrics',
    'settings.data.importNotesBtn': 'Import notes',
    'settings.data.importLyricsBtn': 'Import lyrics',
    'settings.data.importNotesLabel': 'notes',
    'settings.data.importLyricsLabel': 'lyrics',
    'settings.data.importConfirmTitle': 'Import file?',
    'settings.data.importConfirmText': '{count} {label} will be imported. Existing entries for the same songs will be replaced.',
    'settings.data.importAction': 'Import',
    'settings.data.importDone': 'Imported {count} {label}.',
    'settings.data.importWrongKind': 'This file contains the other text type.',
    'settings.data.importInvalid': 'The file is not in the expected Chor App export format.',
    'settings.data.exportTitle': 'Export',
    'settings.data.manageTitle': 'Manage songs',
    'settings.data.dropAudioBtn': 'Delete recordings only',
    'settings.data.manageStorageBtn': 'Manage individual songs',
    'settings.data.renameSongTitle': 'Rename song',
    'settings.data.renameSongPlaceholder': 'Song title',
    'settings.data.renameSongAction': 'Rename',
    'settings.data.renameSongExists': 'A song with this title already exists.',
    'settings.data.renameSongDone': 'Song renamed.',
    'settings.data.deleteTitle': 'Delete',
    'settings.data.deleteHint': "Neither can be undone; files in Dropbox stay untouched either way. \"Delete recordings only\" removes only the audio files — loops, notes, your own lyrics and setlists are kept and reconnect on the next import. \"Delete everything\" also removes those.",
    'settings.data.wipeBtn': 'Delete everything',

    'settings.about.title': 'About the app',
    'settings.about.version': 'Version',
    'settings.about.offline': 'Available offline',
    'settings.about.checkUpdate': 'check',
    'settings.about.checkingUpdate': 'Looking for a newer version …',
    'settings.about.upToDate': "You're already on the latest version.",
    'settings.about.checkUpdateFailed': 'Checking for a newer version failed.',
    'settings.about.checkUpdateUnsupported': "This browser can't check for updates manually.",
    'settings.about.forceUpdate': 'update now',
    'settings.about.forcingUpdate': 'Looking for a newer version — will load it right away if found …',
    'settings.about.forceUpdateApplying': 'Found a newer version, loading it …',
    'settings.about.privacy': 'The app itself makes no automatic network requests and sends no data — everything stays on this device. Using the optional song search (magnifying glass in the player) sends the song title, and artist if known, to the external service selected there (Tidal, Spotify, Deezer, YouTube, or Google).',
    'settings.about.librariesTitle': 'External libraries used:',
    'settings.about.lame': 'MP3 export using <strong>lamejs</strong> (LGPL-3.0), based on <strong>LAME</strong> — <a href="https://lame.sourceforge.net/" target="_blank" rel="noopener noreferrer">lame.sourceforge.net</a>.',
    'settings.about.stretch': 'Slowdown in <strong>HD</strong> mode using <strong>signalsmith-stretch</strong> (MIT) by Geraint Luff / Signalsmith Audio Ltd. — <a href="https://signalsmith-audio.co.uk/code/stretch/" target="_blank" rel="noopener noreferrer">signalsmith-audio.co.uk</a>.',
    'settings.about.errorLogTitle': 'Error log',
    'settings.about.errorLogHint': 'Technical error messages from the app, newest first — helpful when reporting a problem. Stays only on this device.',
    'settings.about.errorLogEmpty': 'No errors recorded.',
    'settings.about.copyLogBtn': 'Copy log',
    'settings.about.clearBtn': 'Clear',
    'settings.about.debugLogTitle': 'Diagnostic log',
    'settings.about.debugLogSwitch': 'Record a detailed log for hard-to-pin-down bugs',
    'settings.about.debugLogAria': 'Record diagnostic log',
    'settings.about.debugLogHint': 'Records technical events (timestamps, states, numbers) — never song titles, file names or names. Useful right before reproducing a problem (e.g. import, then lock the screen); export it here afterwards and send it along when reporting.',
    'settings.about.exportLogBtn': 'Export log',

    'settings.storage.title': 'Storage',
    'settings.storage.measuring': 'measuring …',
    'settings.storage.persistBtn': 'Request persistent storage',

    'onb.step1of5': 'Step 1 of 2',
    'onb.step2of5': 'Step 2 of 5',
    'onb.step3of5': 'Step 2 of 2',
    'onb.step4of5': 'Step 4 of 5',
    'onb.step5of5': 'Step 5 of 5',
    'onb.skip': 'Skip',
    'onb.back': 'Back',
    'onb.next': 'Next',

    'onb.slide1.title': 'Add it to your home screen',
    'onb.slide1.text': 'This makes the app start like any other: its own icon, no browser window, full screen height. Most importantly, the system keeps recordings around longer once the app is installed.',

    'onb.slide2.title': 'Which voice do you sing?',
    'onb.slide2.text': 'Every song has several recordings — one per voice, plus a full mix. Knowing your voice lets the app do two things:',
    'onb.slide2.li1': '<strong>On import</strong>, your voice and the full mix are pre-selected — everything else stays out and saves storage.',
    'onb.slide2.li2': '<strong>In the player</strong>, your voice plays right away, with no need to set it up again for every song.',
    'onb.slide2.footnote': 'All voices stay selectable regardless. Change it under <strong>Settings&nbsp;→&nbsp;My voices</strong>.',

    'onb.slide3.title': 'Keep recordings for good',
    'onb.slide3.text1': 'When storage is tight, the system may delete a web app’s data.',
    'onb.slide3.text2': 'With one tap, we ask it to keep the recordings <strong>permanently</strong>.',

    'onb.slide4.title': 'Practice the hard part',
    'onb.slide4.intro': '<strong>Loop a section.</strong> In the player, under "Practice a section":',
    'onb.slide4.li1': 'Tap <strong>A</strong> where the section should start.',
    'onb.slide4.li2': 'Tap <strong>B</strong> at the end of the section.',
    'onb.slide4.li3': 'Turn on the <strong>switch</strong> next to it — the section now loops until you\'ve got it.',
    'onb.slide4.li4': 'The <strong>save icon</strong> lets you name the section, and it stays saved even after closing.',
    'onb.slide4.speed': '<strong>Practice slower.</strong> The bottom right of the player shows the speed: <strong>1.0×</strong>, <strong>0.85×</strong>, <strong>0.7×</strong> or <strong>0.6×</strong>. The pitch stays the same — it sounds slower, not lower. Together, these two are the core of the app: loop a short section slowly until it sits.',

    'onb.slide5.title': 'Get songs, plan the program',
    'onb.slide5.import': '<strong>Import.</strong> Recordings live in the shared Dropbox folder. Open it in the <strong>browser</strong> — not the Dropbox app, which can\'t download folders as a ZIP —, download it once as a <strong>ZIP file</strong> and pick it under "Settings → Import songs". Before saving, the app shows what it found, and you tick off which voices should actually go onto your phone. Every further import only <strong>adds</strong> — what\'s there stays, missing voices can be loaded later.',
    'onb.slide5.setlists': '<strong>Setlists.</strong> A setlist is a program: the songs in the order they\'re sung. The app moves on by itself at the end of a song. The choir director can hand out a setlist as a plain text file — one title per line —, which you load in under "Setlists".',
    'onb.slide5.note': 'Everything stays on this device. The app sends nothing and needs no internet after the import.',

    'common.cancel': 'Cancel',
    'common.close': 'Close',

    'import.backAria': 'Back to settings',
    'import.intro': 'Recordings live in the shared Dropbox folder. Open Dropbox in the <strong>browser</strong> for this (not the Dropbox app — it can\'t download folders as a ZIP), download the folder once as a ZIP file and pick it here. After that everything is offline on your phone — no Dropbox, no internet needed.',
    'import.pickZipBtn': 'Choose ZIP file',
    'import.pickFolderBtn': 'Choose a folder instead',
    'import.desktopOnly': 'Only available on a computer.',
    'import.goodToKnowTitle': 'Good to know',
    'import.goodToKnow1': 'Every import <strong>adds to</strong> the library. Songs already there are kept.',
    'import.goodToKnow2': 'You can load individual songs or missing voices later.',
    'import.goodToKnow3': 'Before saving you can choose which voices should go onto your phone — that saves storage.',
    'import.goodToKnow4': 'The downloaded ZIP file can be safely deleted afterwards — everything needed is now on the device.',
    'import.libraryTitle': 'Library',
    'import.libSongs': 'Songs',
    'import.libFiles': 'Files',
    'import.libLastImport': 'Last import',
    'import.sheetTitle': 'Selection',
    'import.presetMine': 'My voices',
    'import.presetFull': 'Full',
    'import.presetAll': 'All voices',
    'import.importBtn': 'Import',
    'import.attachSimilarPrefix': 'Copy loops, notes and lyrics from',
    'import.attachSimilarSuffix': 'over to this song',

    'songs.searchPlaceholder': 'Search song …',
    'songs.searchAria': 'Search song',
    'songs.feelingLuckyAria': 'Feeling Lucky — play a random song',
    'songs.recordAria': 'Record',

    'playlists.searchPlaceholder': 'Search song or add a placeholder …',
    'playlists.searchAria': 'Search a song for the setlist',
    'playlists.emptyTitle': 'No setlists yet',
    'playlists.emptyText': 'Create one, or import the choir director\'s text file.',

    'songs.emptyTitle': 'No songs yet',
    'songs.emptyText': 'Download the recordings from Dropbox as a ZIP file and import them here.',
    'songs.notFoundTitle': 'Nothing found',
    'songs.notFoundText': 'No song matches this search.',
    'songs.createPlaceholderSuffix': 'add as placeholder',
    'songs.createPlaceholderHint': 'Create a song that hasn\'t been imported yet — for lyrics, notes or a setlist.',
    'songs.placeholderBadge': 'no recording yet',
    'songs.setlistMissingBadge': 'not in the library',
    'player.placeholderHint': 'No recording imported yet. You can still save lyrics and notes now — they connect automatically on the next import.',
    'player.hdStarve': 'HD could not keep up in the background: with the screen off this device throttles its CPU, and the HD time-stretcher then misses real time. That is the stuttering you heard.',
    'player.hdStarveAction': 'Switch to Standard',

    'lightshow.backAria': 'Back to settings',
    'lightshow.noVoiceHint': 'No voice part chosen yet — the show will use the soprano block for now. Change it under <strong>Settings → My voices</strong>, or set it here just for the show:',
    'lightshow.voicePickerAria': 'Voice for the light show',
    'lightshow.voicePrefix': 'You light up as',
    'lightshow.showsTitle': 'Choose a show',
    'lightshow.startBtn': 'Start show',
    'lightshow.rehearsalLabel': 'Rehearsal — starts right away instead of waiting for the grid point',
    'lightshow.rehearsalAria': 'Rehearsal',
    'lightshow.rehearsalHint': 'Turns off again once you close this view — otherwise someone could end up on stage in rehearsal mode.',
    'lightshow.syncTitle': 'Synchronise time',
    'lightshow.syncInfo': 'First, synchronise this phone with the PTB time server once. The measured correction is then used for previews and shows.',
    'lightshow.syncBtn': 'Synchronise with server time',
    'lightshow.previewBtn': 'Play preview',
    'lightshow.hintBlock': 'Turn up the screen brightness by hand before the concert — the app can’t do that itself. Don’t lock the phone during the show, and synchronise with server time above before starting.',
    'lightshow.seizureWarning': 'The shows use bright, changing areas of colour. If you’re light-sensitive or prone to seizures, better sit this one out or pick "Sea of stars".',
    'lightshow.reducedMotionHint': 'This device prefers reduced motion — "Sea of stars" is pre-selected because of that. The other shows can still be started.',
    'lightshow.recommendedBadge': 'Recommended',

    'lightshow.show.sterne.name': 'Sea of stars',
    'lightshow.show.sterne.desc': 'A shared deep night carries calm coloured constellations across all voice sections.',
    'lightshow.show.puls.name': 'Heartbeat',
    'lightshow.show.puls.desc': 'The whole choir beats together in red, joined by coloured echoes and a white finale.',
    'lightshow.show.welle.name': 'Aurora',
    'lightshow.show.welle.desc': 'Every section stays alight while a bright edge travels through changing aurora colours.',
    'lightshow.show.finale.name': 'Finale',
    'lightshow.show.finale.desc': 'Large shared fields, symmetrical accents and bold white cuts build toward the climax.',
    'lightshow.show.prisma.name': 'Prism',
    'lightshow.show.prisma.desc': 'Colour chords rotate and mirror before the whole choir joins in shared neon fields.',
    'lightshow.show.domino.name': 'Domino',
    'lightshow.show.domino.desc': 'A full carpet of colour remains while bright accents travel through it and become tutti fields.',
    'lightshow.show.dialog.name': 'Dialogue',
    'lightshow.show.dialog.desc': 'Shared statements alternate with answers from the stage halves, outer voices and inner voices.',
    'lightshow.show.kaleidoskop.name': 'Kaleidoscope',
    'lightshow.show.kaleidoskop.desc': 'Fast symmetrical colour fields continually recombine and regularly resolve into tutti.',

    'lightshow.syncLevel.unkritisch': 'forgives clocks that run off',
    'lightshow.syncLevel.hoch': 'forgives small differences',
    'lightshow.syncLevel.mittel': 'needs reasonably set clocks',
    'lightshow.syncLevel.empfindlich': 'needs well-set clocks',



    'lightshow.ntpcal.dialogTitle': 'Sync with internet time?',
    'lightshow.ntpcal.dialogText': 'This sends a one-off request to PTB’s atomic clock (Physikalisch-Technische Bundesanstalt, Germany’s national metrology institute, uhr.ptb.de) to look up the current time. No other data is transmitted — just this one time lookup.',
    'lightshow.ntpcal.dialogOk': 'Sync',
    'lightshow.ntpcal.dialogCancel': 'Cancel',
    'lightshow.ntpcal.statusChecking': 'Checking time server …',
    'lightshow.ntpcal.statusDone': 'Done — time correction set to {value} (round-trip {rtt}, estimated accuracy ±{uncertainty}).',
    'lightshow.ntpcal.statusClockError': 'The device clock differs by {value}. Please correct the device date and time first.',
    'lightshow.ntpcal.statusError': 'Time server unreachable — please try again later.',
  },
  pl: {
    'nav.songs': 'Utwory',
    'nav.playlists': 'Setlisty',
    'nav.player': 'Odtwarzacz',
    'nav.settings': 'Ustawienia',

    'tabs.loops': 'Loopy',
    'tabs.rec': 'REC',
    'tabs.lyrics': 'Tekst',
    'tabs.notes': 'Notatki',
    'scores.hintLabel': 'Dostępne nuty',
    'scores.modalTitle': 'Nuty',

    'settings.importBtn': 'Importuj utwory',
    'settings.personal.title': 'Make it yours!',
    'settings.personal.behaviorTitle': 'Zachowanie',
    'settings.personal.displayTitle': 'Wygląd',
    'settings.personal.tabHint': 'Zakładka widoczna jako pierwsza po otwarciu utworu.',
    'settings.personal.tabGroupAria': 'Domyślna zakładka w odtwarzaczu',
    'settings.personal.language': 'Język',
    'settings.personal.accent': 'Kolor akcentu',
    'settings.personal.presentTitle': 'Wyświetlanie tekstu dla innych',
    'settings.personal.presentHint': 'Kolor dużego, pełnoekranowego wyświetlacza do wspólnego czytania (przycisk pełnego ekranu przy tekście).',
    'settings.personal.presentThemeDark': 'Biały na czarnym',
    'settings.personal.presentThemeLight': 'Czarny na białym',
    'settings.personal.searchTitle': 'Wyszukiwanie utworu',
    'settings.personal.searchHint': 'Usługa używana przez ikonę lupy w odtwarzaczu. Długie przytrzymanie pozwala jednorazowo wybrać inną usługę.',
    'settings.personal.searchPrivacyHint': 'Dotknięcie lupy w odtwarzaczu wysyła tytuł utworu (a jeśli jest znany, także wykonawcę) do usługi wybranej tutaj.',

    'songsearch.dialogTitle': 'Wyszukiwanie zewnętrzne',
    'songsearch.dialogPrefix': 'Otwiera ',
    'songsearch.dialogSuffix': ' i wysyła tam tytuł utworu, aby go wyszukać.',
    'songsearch.dialogServiceLabel': 'Usługa',
    'songsearch.dialogOk': 'Pasuje',
    'songsearch.dialogCancel': 'Nie teraz',

    'settings.voices.title': 'Moje głosy',
    'settings.voices.hint': 'Można wybrać kilka — dla osób śpiewających różnymi głosami. Decyduje, które ścieżki są wstępnie zaznaczone przy imporcie i który głos odtwarzacz pokazuje jako pierwszy.',

    'settings.lightshow.title': 'Pokaz świateł',
    'settings.lightshow.hint': 'Osiem scenicznych pokazów na koncert: pełnoekranowe kolory traktują każdy głos jako osobny blok i działają synchronicznie według zegara systemowego.',
    'settings.lightshow.openBtn': 'Otwórz pokaz świateł',

    'settings.audio.title': 'Ustawienia audio',

    'settings.bike.title': 'Tryb rowerowy',
    'settings.bike.hint': 'Przy jednej słuchawce: jeśli głos (np. bas) jest mocno przesunięty na jedną stronę, w drugim uchu może być w ogóle niesłyszalny.',
    'settings.bike.normal': 'Normalny',
    'settings.bike.mono': 'Mono',
    'settings.bike.swap': 'Zamień',
    'settings.normalization.label': 'Normalizuj głośność',
    'settings.normalization.aria': 'Normalizuj głośność',
    'settings.normalization.hint': 'Wyrównuje różnice głośności między nagraniami.',
    'settings.normalization.confirmTitle': 'Normalizować głośność?',
    'settings.normalization.confirmText': 'Każde nagranie jest analizowane raz na tym urządzeniu, a wynik zostaje zapisany. Analiza wstrzymuje się podczas odtwarzania, nagrywania lub importu. Bardzo długie lub duże nagrania są pomijane. Oryginalne pliki pozostają bez zmian.',
    'settings.normalization.activate': 'Aktywuj',
    'settings.normalization.cancel': 'Anuluj',
    'settings.normalization.progress': 'Analiza: przetworzono {done} z {total} nagrań',
    'settings.normalization.counts': '{analyzed} z {total} powodzeniem, {failed} błędów',
    'settings.normalization.retry': 'Spróbuj ponownie',
    'settings.normalization.clearAll': 'Analizuj ponownie',
    'settings.normalization.clearAllConfirmTitle': 'Usunąć wszystkie wyniki analizy?',
    'settings.normalization.clearAllConfirmText': 'Usuwa każdy zapisany wynik normalizacji (przeanalizowany, pominięty, nieudany) dla wszystkich utworów na tym urządzeniu. Przydatne do eksperymentowania — jeśli normalizacja jest nadal włączona, wszystko zostanie ponownie przeanalizowane. Oryginalne pliki pozostają nietknięte.',
    'settings.normalization.clearAllConfirm': 'Usuń',
    'settings.normalization.filter.all': 'Wszystkie',
    'settings.normalization.filter.analyzed': 'Gotowe',
    'settings.normalization.filter.problems': 'Błędy',
    'settings.normalization.details.emptyFilter': 'Brak wpisów dla tego filtra.',
    'settings.normalization.reason.duration': 'Pominięto: nagranie dłuższe niż 10 minut.',
    'settings.normalization.reason.compressed': 'Pominięto: plik skompresowany przekracza 60 MiB.',
    'settings.normalization.reason.pcm': 'Pominięto: szacowane PCM przekracza 128 MiB.',
    'settings.normalization.reason.metadataInvalid': 'Pominięto: częstotliwość próbkowania lub liczba kanałów niejasna.',
    'settings.normalization.reason.durationInvalid': 'Pominięto: czas trwania niejasny.',
    'settings.normalization.reason.metadataTimeout': 'Pominięto: przekroczono czas odczytu metadanych.',
    'settings.normalization.reason.decoderUnsupported': 'Pominięto: analiza offline nieobsługiwana.',
    'settings.normalization.reason.decodeError': 'Błąd: dekodowanie nie powiodło się.',
    'settings.normalization.reason.storageError': 'Błąd: błąd bazy danych.',
    'settings.normalization.reason.crashGuard': 'Błąd: przerwano (aplikacja zamknięta?).',
    'settings.normalization.reason.unknown': 'Błąd: nieznana przyczyna.',
    'settings.normalization.unavailable': 'Normalizacja nie jest dostępna w tym trybie odtwarzania.',
    'settings.normalization.paused.playback': 'Wstrzymano: wznowi się po zakończeniu odtwarzania/podglądu.',
    'settings.normalization.paused.recording': 'Wstrzymano: wznowi się po zakończeniu nagrywania.',
    'settings.normalization.paused.import': 'Wstrzymano: wznowi się po zakończeniu importu.',
    'settings.normalization.details.title': 'Wyniki analizy dla poszczególnych plików',
    'settings.normalization.details.retryFile': 'Spróbuj ponownie ten plik',
    'settings.normalization.details.showAll': 'Pokaż wszystkie {count}',
    'settings.normalization.details.technical': 'Szczegóły techniczne',
    'settings.normalization.detail.minutes': '{time} minut',
    'settings.normalization.detail.fileInfo': '{duration} · {channels} · {rate}',
    'settings.normalization.detail.analyzed': 'Dekodowanie {decodeS} s · Analiza {analysisS} s · PCM {pcmMiB} MiB',
    'settings.normalization.detail.analyzedHint': 'Szacowana pamięć PCM zdekodowanego bufora analizy — nie całkowita pamięć przeglądarki/karty.',
    'settings.normalization.detail.duration': 'Pominięto: nagranie trwa {duration}. Dozwolone jest najwyżej {limit}.',
    'settings.normalization.detail.compressed': 'Pominięto: plik ma {sizeMiB} MiB. Dozwolone jest najwyżej {limitMiB} MiB.',
    'settings.normalization.detail.pcm': 'Pominięto: szacowana pamięć audio wynosi {estimatedMiB} MiB. Dozwolone jest {limitMiB} MiB.',
    'settings.normalization.detail.metadataInvalid': 'Pominięto: nie udało się wiarygodnie ustalić częstotliwości próbkowania lub liczby kanałów.',
    'settings.normalization.detail.durationInvalid': 'Pominięto: nie udało się wiarygodnie ustalić czasu trwania nagrania.',
    'settings.normalization.detail.metadataTimeout': 'Pominięto: odczyt metadanych trwał zbyt długo.',
    'settings.normalization.detail.decoderUnsupported': 'Pominięto: ta przeglądarka nie obsługuje analizy audio offline.',
    'settings.normalization.detail.decodeError': 'Błąd: przeglądarka nie mogła zdekodować pliku audio. Format może być nieobsługiwany lub plik jest uszkodzony.',
    'settings.normalization.detail.storageError': 'Błąd: wystąpił błąd podczas dostępu do bazy danych.',
    'settings.normalization.detail.crashGuard': 'Błąd: analiza została przerwana, zanim mogła bezpiecznie się zakończyć — możliwe, że przez zamknięcie aplikacji.',
    'settings.normalization.detail.unknown': 'Błąd: nie udało się ustalić dokładnej przyczyny.',
    'settings.normalization.channels.mono': 'Mono',
    'settings.normalization.channels.stereo': 'Stereo',
    'settings.normalization.channels.multi': '{count} kanałów',
    'settings.normalization.crashGuard.message': 'Ostatnia analiza pliku „{fileName}” została nieoczekiwanie przerwana. Automatyczna analiza została wstrzymana zapobiegawczo.',
    'settings.normalization.crashGuard.resume': 'Wznów',

    'settings.screen.title': 'Ekran i tło',
    'settings.screen.keepOn': 'Ekran włączony, dopóki utwór jest otwarty',
    'settings.screen.keepOnAria': 'Ekran włączony',
    'settings.screen.hint': 'Zapobiega tylko automatycznemu przygaszaniu przy bezczynności — nie pomoże, gdy sam zablokujesz telefon przyciskiem.',
    'settings.screen.bgHelpToggle': 'Odtwarzanie w tle nie działa?',
    'settings.screen.bgHelpIntro': 'Jeśli odtwarzanie przerywa się zaraz po zablokowaniu telefonu, to nie wina tej aplikacji: Android decyduje, czy aplikacja webowa może działać w tle, a sterują tym dwa ustawienia systemowe — oba trzeba zmienić ręcznie, żadna strona nie może ustawić ich sama.',
    'settings.screen.step1': 'Ustawienia Androida → <strong>Aplikacje</strong> → otwórz swoją przeglądarkę (np. <strong>Vanadium</strong> lub <strong>Chrome</strong> — tę, w której użyto „Dodaj do ekranu głównego").',
    'settings.screen.step2': '<strong>Bateria</strong> → wybierz <strong>Bez ograniczeń</strong>. W przeciwnym razie Android zamknie przeglądarkę w tle, gdy tylko ekran zgaśnie.',
    'settings.screen.step3': '<strong>Powiadomienia</strong> → zezwól. Android wymaga widocznego powiadomienia — bez niego żadna aplikacja webowa nie może grać w tle.',
    'settings.screen.grapheneNote': 'Bez usług Google Play — np. na GrapheneOS — „Dodaj do ekranu głównego" zwykle tworzy tylko skrót, a nie osobną ikonę aplikacji z własnymi uprawnieniami. Oba ustawienia dotyczą wtedy samej przeglądarki, nie osobnej ikony „BVG".',
    'settings.screen.notifyBtn': 'Zezwól na powiadomienia dla tej strony',

    'settings.perf.title': 'Kompatybilność i wydajność',
    'settings.perf.modeHint': 'Jak liczone jest spowolnienie przy 0,85×, 0,7× i 0,6×.',
    'settings.perf.modeStandard': 'Standard',
    'settings.perf.modeHd': 'HD',
    'settings.perf.hdHint': 'HD brzmi wyraźniej przy wolniejszym tempie, ale wymaga więcej mocy. Przy zacinaniu lub nagrzewaniu wybierz Standard.',
    'settings.perf.hdUnsupported': 'To urządzenie nie obsługuje HD — Standard nadal działa.',
    'settings.perf.webkitHint': 'Safari może nadal błędnie odtwarzać zwolniony dźwięk. Dlatego HD jest tam wyłączony; można go sprawdzić przez „Spróbuj mimo to”.',
    'settings.perf.webkitForceGraph': 'Spróbuj mimo to',
    'settings.perf.webkitForceGraphAria': 'Wymuś tryb kanałów i HD mimo znanego błędu Safari',
    'settings.perf.webkitForceGraphHint': 'Jeśli brzmi urywanie albo wysokość dźwięku jest błędna, błąd nie jest jeszcze naprawiony — wyłącz to ponownie.',
    'settings.perf.introTitle': 'Tryb HD',
    'settings.perf.introText': 'Tryb HD podnosi jakość dźwięku przy wolniejszym odtwarzaniu, ale na starszych telefonach może to być za dużo. Można to cofnąć w Ustawieniach. Wypróbować teraz?',
    'settings.perf.introActivate': 'Tak, wypróbuj',
    'settings.perf.introStay': 'Nie, dziękuję',
    'settings.perf.rtLabel': 'Tempo odtwarzania:',
    'settings.perf.rtSuffix': 'czasu rzeczywistego',
    'settings.perf.rebuildBtn': 'Odbuduj wyjście audio',
    'settings.perf.rebuildHint': 'Spróbuj tego, jeśli masz problemy z dźwiękiem.',
    'settings.perf.rebuildDone': 'Wyjście audio odbudowane.',
    'rec.input.narrowband': 'Mikrofon działa z jakością telefoniczną — to typowe, gdy słuchawki Bluetooth podczas nagrywania przełączają się na profil zestawu głośnomówiącego. Wtedy utwór także brzmi głucho. Pomogą słuchawki przewodowe albo wyłączenie Bluetooth.',
    'rec.input.bluetooth': 'Nagrywanie przez zestaw słuchawkowy Bluetooth. Wiele słuchawek przełącza się wtedy na jakość telefoniczną — także podczas odtwarzania. Słuchawki przewodowe brzmią znacznie lepiej.',
    'rec.input.bluetoothAfterUse': 'Android mógł pozostać w profilu głośnomówiącym Bluetooth. Rozłącz i ponownie połącz Bluetooth lub słuchawki. „Odbuduj wyjście audio” odbudowuje tylko graf Web Audio i nie może zresetować profilu Bluetooth Androida.',
    'settings.perf.advToggle': 'Zaawansowane: ustawienia rozciągacza',
    'settings.perf.advIntro': 'Działa natychmiast, także w trakcie odtwarzania. Do eksperymentów — ustawienia domyślne są dobrane świadomie.',
    'settings.perf.advGroupSound': 'Brzmienie',
    'settings.perf.advGroupCost': 'Obciążenie',
    'settings.perf.advFormantComp': 'Korekta formantów',
    'settings.perf.advFormantCompHint': 'Powinna tu zostać wyłączona: resampling obniża wysokość i formanty razem, a podniesienie przywraca oba razem. Włączona brzmi ciemniej, nie lepiej.',
    'settings.perf.advFormantSemi': 'Przesuń formanty',
    'settings.perf.advFormantBase': 'Ton podstawowy formantów',
    'settings.perf.advFormantBaseAuto': 'automatycznie',
    'settings.perf.advTonality': 'Granica tonalności',
    'settings.perf.advPresetDefault': 'Standard',
    'settings.perf.advPresetCheap': 'Oszczędny',
    'settings.perf.advBlock': 'Długość bloku',
    'settings.perf.advBlockAuto': 'wg ustawienia',
    'settings.perf.advInterval': 'Krok',
    'settings.perf.advIntervalAuto': 'automatycznie',
    'settings.perf.advSplit': 'Rozłóż obliczenia na kwanty',
    'settings.perf.advSplitHint': 'Rozkłada pracę jednego bloku analizy na kilka kwantów renderowania. Zmierzono, że nie kosztuje mocy, tylko ćwierć więcej opóźnienia — dlatego jest domyślnie włączone.',
    'settings.perf.advLatency': 'Opóźnienie rozciągacza:',
    'settings.perf.advSemitones': 'Korekta wysokości:',
    'settings.perf.advReset': 'Resetuj',
    'settings.perf.advUnitSemi': 'półtonów',
    'settings.perf.advIsDefault': 'fabrycznie',
    'settings.perf.advIsDefaultSuffix': ' · fabrycznie',
    'settings.perf.advPresetIsDefault': 'Ustawienie domyślne',
    'settings.perf.advUnitLatency': 'opóźnienia',
    'settings.perf.advSplitInactive': 'Bez efektu, gdy wybrane jest ustawienie wstępne: biblioteka sama dobiera tam długość bloku i krok. Ustaw własną długość bloku, wtedy przełącznik zadziała.',
    'settings.perf.advCostHint': 'Realne oszczędności daje tylko krok albo ustawienie „Oszczędny": większy krok to mniej bloków analizy na sekundę. Długość bloku prawie nie zmienia obciążenia — decyduje o rozdzielczości i opóźnieniu.',
    'settings.perf.advAb': 'A/B',
    'settings.perf.advAbAria': 'Porównaj ustawienie standardowe z własnym',
    'settings.perf.advAbHint': 'Słuchasz teraz ustawienia domyślnego do porównania — twoje własne wartości pozostają zapisane bez zmian.',
    'settings.perf.advCopy': 'Kopiuj',
    'settings.perf.advCopied': 'Ustawienia skopiowane do schowka.',
    'settings.perf.advOn': 'wł.',
    'settings.perf.advOff': 'wył.',

    'settings.help.title': 'Pomoc',
    'settings.help.intro': 'Nagrania trafiają do aplikacji jako plik ZIP z Dropboxa. Poniższy przycisk pokazuje krok po kroku, jak zrobić to na iPhonie i na Androidzie.',
    'settings.help.howToBtn': 'Jak wgrać utwory do aplikacji?',
    'settings.help.replayOnboarding': 'Obejrzyj wprowadzenie ponownie',

    'settings.data.title': 'Dane i kopia zapasowa',
    'settings.data.backupTitle': 'Kopia zapasowa',
    'settings.data.backupBtn': 'Kopia zapasowa',
    'settings.data.restoreBtn': 'Przywróć',
    'settings.data.printNotesBtn': 'Notatki',
    'settings.data.printLyricsBtn': 'Własne teksty',
    'settings.data.importNotesBtn': 'Importuj notatki',
    'settings.data.importLyricsBtn': 'Importuj teksty',
    'settings.data.importNotesLabel': 'notatek',
    'settings.data.importLyricsLabel': 'tekstów',
    'settings.data.importConfirmTitle': 'Zaimportować plik?',
    'settings.data.importConfirmText': 'Zaimportowanych zostanie: {count} {label}. Istniejące wpisy dla tych samych utworów zostaną zastąpione.',
    'settings.data.importAction': 'Importuj',
    'settings.data.importDone': 'Zaimportowano: {count} {label}.',
    'settings.data.importWrongKind': 'Ten plik zawiera drugi rodzaj tekstu.',
    'settings.data.importInvalid': 'Plik nie ma oczekiwanego formatu eksportu Chor App.',
    'settings.data.exportTitle': 'Eksportuj',
    'settings.data.manageTitle': 'Zarządzaj utworami',
    'settings.data.dropAudioBtn': 'Usuń tylko nagrania',
    'settings.data.manageStorageBtn': 'Zarządzaj pojedynczymi utworami',
    'settings.data.renameSongTitle': 'Zmień nazwę utworu',
    'settings.data.renameSongPlaceholder': 'Tytuł utworu',
    'settings.data.renameSongAction': 'Zmień nazwę',
    'settings.data.renameSongExists': 'Utwór o tym tytule już istnieje.',
    'settings.data.renameSongDone': 'Zmieniono nazwę utworu.',
    'settings.data.deleteTitle': 'Usuń',
    'settings.data.deleteHint': 'Obu czynności nie da się cofnąć; pliki w Dropboxie w każdym przypadku pozostają nietknięte. „Usuń tylko nagrania” usuwa tylko pliki audio — loopy, notatki, własne teksty i setlisty pozostają zachowane i połączą się ponownie przy kolejnym imporcie. „Usuń wszystko” usuwa dodatkowo także je.',
    'settings.data.wipeBtn': 'Usuń wszystko',

    'settings.about.title': 'O aplikacji',
    'settings.about.version': 'Wersja',
    'settings.about.offline': 'Dostępna offline',
    'settings.about.checkUpdate': 'sprawdź',
    'settings.about.checkingUpdate': 'Szukam nowszej wersji …',
    'settings.about.upToDate': 'Masz już najnowszą wersję.',
    'settings.about.checkUpdateFailed': 'Sprawdzanie nowszej wersji nie powiodło się.',
    'settings.about.checkUpdateUnsupported': 'W tej przeglądarce nie można ręcznie sprawdzić aktualizacji.',
    'settings.about.forceUpdate': 'zaktualizuj teraz',
    'settings.about.forcingUpdate': 'Szukam nowszej wersji — po znalezieniu od razu ją wczytam …',
    'settings.about.forceUpdateApplying': 'Znaleziono nowszą wersję, wczytuję …',
    'settings.about.privacy': 'Sama aplikacja nie wysyła automatycznie żadnych zapytań sieciowych ani danych — wszystko pozostaje na tym urządzeniu. Korzystanie z opcjonalnego wyszukiwania utworu (lupka w odtwarzaczu) przesyła tytuł utworu, a jeśli jest znany, także wykonawcę, do wybranej tam zewnętrznej usługi (Tidal, Spotify, Deezer, YouTube lub Google).',
    'settings.about.librariesTitle': 'Użyte biblioteki zewnętrzne:',
    'settings.about.lame': 'Eksport MP3 z użyciem <strong>lamejs</strong> (LGPL-3.0), opartego na <strong>LAME</strong> — <a href="https://lame.sourceforge.net/" target="_blank" rel="noopener noreferrer">lame.sourceforge.net</a>.',
    'settings.about.stretch': 'Spowolnienie w trybie <strong>HD</strong> z użyciem <strong>signalsmith-stretch</strong> (MIT) autorstwa Geraint Luff / Signalsmith Audio Ltd. — <a href="https://signalsmith-audio.co.uk/code/stretch/" target="_blank" rel="noopener noreferrer">signalsmith-audio.co.uk</a>.',
    'settings.about.errorLogTitle': 'Dziennik błędów',
    'settings.about.errorLogHint': 'Techniczne komunikaty błędów aplikacji, najnowsze na górze — pomocne przy zgłaszaniu problemu. Pozostaje tylko na tym urządzeniu.',
    'settings.about.errorLogEmpty': 'Brak zarejestrowanych błędów.',
    'settings.about.copyLogBtn': 'Kopiuj dziennik',
    'settings.about.clearBtn': 'Wyczyść',
    'settings.about.debugLogTitle': 'Dziennik diagnostyczny',
    'settings.about.debugLogSwitch': 'Zapisuj szczegółowy dziennik dla trudnych do uchwycenia błędów',
    'settings.about.debugLogAria': 'Zapisuj dziennik diagnostyczny',
    'settings.about.debugLogHint': 'Zapisuje techniczne zdarzenia (znaczniki czasu, stany, liczby) — nigdy tytuły utworów, nazwy plików ani nazwiska. Przydatne tuż przed odtworzeniem problemu (np. import, potem zablokowanie ekranu); potem wyeksportuj tutaj i dołącz przy zgłoszeniu.',
    'settings.about.exportLogBtn': 'Eksportuj dziennik',

    'settings.storage.title': 'Pamięć',
    'settings.storage.measuring': 'sprawdzanie …',
    'settings.storage.persistBtn': 'Poproś o trwałe przechowywanie',

    'onb.step1of5': 'Krok 1 z 2',
    'onb.step2of5': 'Krok 2 z 5',
    'onb.step3of5': 'Krok 2 z 2',
    'onb.step4of5': 'Krok 4 z 5',
    'onb.step5of5': 'Krok 5 z 5',
    'onb.skip': 'Pomiń',
    'onb.back': 'Wstecz',
    'onb.next': 'Dalej',

    'onb.slide1.title': 'Dodaj do ekranu głównego',
    'onb.slide1.text': 'Dzięki temu aplikacja startuje jak każda inna: własna ikona, bez okna przeglądarki, pełny ekran. Przede wszystkim system dłużej przechowuje nagrania, gdy aplikacja jest zainstalowana.',

    'onb.slide2.title': 'Jakim głosem śpiewasz?',
    'onb.slide2.text': 'Do każdego utworu jest kilka nagrań — jedno na głos i jeden pełny miks. Znając twój głos, aplikacja wie dwie rzeczy:',
    'onb.slide2.li1': '<strong>Przy imporcie</strong> twój głos i pełny miks są wstępnie zaznaczone — reszta zostaje pominięta, co oszczędza miejsce.',
    'onb.slide2.li2': '<strong>W odtwarzaczu</strong> od razu słychać twój głos, bez ustawiania go na nowo przy każdym utworze.',
    'onb.slide2.footnote': 'Wszystkie głosy nadal można wybrać. Zmienisz to w <strong>Ustawienia&nbsp;→&nbsp;Moje głosy</strong>.',

    'onb.slide3.title': 'Zachowaj nagrania na stałe',
    'onb.slide3.text1': 'Gdy brakuje miejsca, system może usunąć dane aplikacji internetowej.',
    'onb.slide3.text2': 'Jednym dotknięciem prosimy, aby zachował nagrania <strong>na stałe</strong>.',

    'onb.slide4.title': 'Ćwicz trudny fragment',
    'onb.slide4.intro': '<strong>Powtarzaj fragment.</strong> W odtwarzaczu, w sekcji „Ćwicz fragment":',
    'onb.slide4.li1': 'Dotknij <strong>A</strong> w miejscu, gdzie fragment ma się zaczynać.',
    'onb.slide4.li2': 'Dotknij <strong>B</strong> na końcu fragmentu.',
    'onb.slide4.li3': 'Włącz <strong>przełącznik</strong> obok — fragment gra teraz w pętli, aż go opanujesz.',
    'onb.slide4.li4': '<strong>Ikona dyskietki</strong> pozwala nazwać fragment i zapisuje go na stałe, nawet po zamknięciu.',
    'onb.slide4.speed': '<strong>Ćwicz wolniej.</strong> W prawym dolnym rogu odtwarzacza jest prędkość: <strong>1,0×</strong>, <strong>0,85×</strong>, <strong>0,7×</strong> lub <strong>0,6×</strong>. Wysokość dźwięku pozostaje taka sama — brzmi wolniej, nie niżej. Oba te elementy razem to sedno aplikacji: powtarzać krótki fragment wolno, aż zasiądzie.',

    'onb.slide5.title': 'Pobierz utwory, zaplanuj program',
    'onb.slide5.import': '<strong>Import.</strong> Nagrania znajdują się we współdzielonym folderze Dropbox. Otwórz go w <strong>przeglądarce</strong> — nie w aplikacji Dropbox, która nie umie pobrać folderu jako ZIP —, pobierz go raz jako plik <strong>ZIP</strong> i wybierz go w „Ustawienia → Importuj utwory". Przed zapisaniem aplikacja pokazuje, co znalazła, a ty zaznaczasz, które głosy naprawdę mają trafić na telefon. Każdy kolejny import tylko <strong>dodaje</strong> — to, co jest, zostaje, brakujące głosy można doładować później.',
    'onb.slide5.setlists': '<strong>Setlisty.</strong> Setlista to program: utwory w kolejności, w jakiej są śpiewane. Po zakończeniu utworu aplikacja sama przechodzi dalej. Prowadzący chór może rozesłać setlistę jako zwykły plik tekstowy — jeden tytuł na linię —, a ty wczytujesz ją w „Setlisty".',
    'onb.slide5.note': 'Wszystko pozostaje na tym urządzeniu. Aplikacja niczego nie wysyła i po imporcie nie potrzebuje już internetu.',

    'common.cancel': 'Anuluj',
    'common.close': 'Zamknij',

    'import.backAria': 'Wróć do ustawień',
    'import.intro': 'Nagrania znajdują się we współdzielonym folderze Dropbox. Otwórz Dropbox w <strong>przeglądarce</strong> (nie w aplikacji Dropbox — ta nie potrafi pobrać folderu jako ZIP), pobierz folder raz jako plik ZIP i wybierz go tutaj. Potem wszystko działa offline na telefonie — bez Dropboxa, bez internetu.',
    'import.pickZipBtn': 'Wybierz plik ZIP',
    'import.pickFolderBtn': 'Wybierz zamiast tego folder',
    'import.desktopOnly': 'Dostępne tylko na komputerze.',
    'import.goodToKnowTitle': 'Warto wiedzieć',
    'import.goodToKnow1': 'Każdy import <strong>uzupełnia</strong> bibliotekę. Utwory, które już tam są, pozostają.',
    'import.goodToKnow2': 'Pojedyncze utwory lub brakujące głosy możesz doładować później.',
    'import.goodToKnow3': 'Przed zapisaniem możesz wybrać, które głosy mają trafić na telefon — to oszczędza miejsce.',
    'import.goodToKnow4': 'Pobrany plik ZIP można potem bezpiecznie usunąć — wszystko potrzebne jest już na urządzeniu.',
    'import.libraryTitle': 'Biblioteka',
    'import.libSongs': 'Utwory',
    'import.libFiles': 'Pliki',
    'import.libLastImport': 'Ostatni import',
    'import.sheetTitle': 'Wybór',
    'import.presetMine': 'Moje głosy',
    'import.presetFull': 'Full',
    'import.presetAll': 'Wszystkie głosy',
    'import.importBtn': 'Importuj',
    'import.attachSimilarPrefix': 'Przenieś loopy, notatki i tekst z',
    'import.attachSimilarSuffix': 'do tego utworu',

    'songs.searchPlaceholder': 'Szukaj utworu …',
    'songs.searchAria': 'Szukaj utworu',
    'songs.feelingLuckyAria': 'Feeling Lucky — odtwórz losowy utwór',
    'songs.recordAria': 'Nagraj',

    'playlists.searchPlaceholder': 'Szukaj utworu lub dodaj placeholder …',
    'playlists.searchAria': 'Szukaj utworu do setlisty',
    'playlists.emptyTitle': 'Jeszcze brak setlist',
    'playlists.emptyText': 'Utwórz jedną albo zaimportuj plik tekstowy od prowadzącego chór.',

    'songs.emptyTitle': 'Jeszcze brak utworów',
    'songs.emptyText': 'Pobierz nagrania z Dropboxa jako plik ZIP i zaimportuj je tutaj.',
    'songs.notFoundTitle': 'Nic nie znaleziono',
    'songs.notFoundText': 'Żaden utwór nie pasuje do tego wyszukiwania.',
    'songs.createPlaceholderSuffix': 'dodaj jako placeholder',
    'songs.createPlaceholderHint': 'Utwórz jeszcze niezaimportowany utwór — na tekst, notatki lub do setlisty.',
    'songs.placeholderBadge': 'jeszcze bez nagrania',
    'songs.setlistMissingBadge': 'brak w bibliotece',
    'player.placeholderHint': 'Nagranie nie zostało jeszcze zaimportowane. Możesz już teraz zapisać tekst i notatki — połączą się automatycznie przy kolejnym imporcie.',
    'player.hdStarve': 'HD nie nadążał w tle: przy wyłączonym ekranie urządzenie ogranicza moc obliczeniową i rozciąganie czasu w trybie HD przestaje działać w czasie rzeczywistym. Stąd przerywanie dźwięku.',
    'player.hdStarveAction': 'Przełącz na Standard',

    'lightshow.backAria': 'Wróć do ustawień',
    'lightshow.noVoiceHint': 'Nie wybrano jeszcze głosu — pokaz na razie używa bloku sopranu. Zmień to w <strong>Ustawienia → Moje głosy</strong>, albo ustaw tylko dla pokazu tutaj:',
    'lightshow.voicePickerAria': 'Głos na pokaz świateł',
    'lightshow.voicePrefix': 'Świecisz jako',
    'lightshow.showsTitle': 'Wybierz pokaz',
    'lightshow.startBtn': 'Uruchom pokaz',
    'lightshow.rehearsalLabel': 'Próba — zaczyna od razu, bez czekania na punkt siatki czasowej',
    'lightshow.rehearsalAria': 'Próba',
    'lightshow.rehearsalHint': 'Po zamknięciu tego widoku znowu jest wyłączona — inaczej ktoś mógłby stanąć na scenie w trybie próby.',
    'lightshow.syncTitle': 'Synchronizacja czasu',
    'lightshow.syncInfo': 'Na początku zsynchronizuj zegar telefonu z serwerem czasu PTB. Wyznaczona korekta będzie używana w podglądach i pokazach.',
    'lightshow.syncBtn': 'Synchronizuj z czasem serwera',
    'lightshow.previewBtn': 'Odtwórz podgląd',
    'lightshow.hintBlock': 'Przed koncertem ręcznie zwiększ jasność ekranu — aplikacja nie może zrobić tego sama. Nie blokuj telefonu podczas pokazu i przed startem zsynchronizuj czas z serwerem.',
    'lightshow.seizureWarning': 'Pokazy operują jasnymi, zmieniającymi się barwami. Osoby wrażliwe na światło lub podatne na napady lepiej niech nie biorą udziału albo wybiorą „Morze gwiazd".',
    'lightshow.reducedMotionHint': 'To urządzenie preferuje mniej ruchu — dlatego wybrano wstępnie „Morze gwiazd". Pozostałe pokazy nadal można uruchomić.',
    'lightshow.recommendedBadge': 'Polecane',

    'lightshow.show.sterne.name': 'Morze gwiazd',
    'lightshow.show.sterne.desc': 'Wspólna głęboka noc niesie spokojne kolorowe konstelacje przez wszystkie głosy.',
    'lightshow.show.puls.name': 'Bicie serca',
    'lightshow.show.puls.desc': 'Cały chór pulsuje razem na czerwono, z kolorowymi echami i białym finałem.',
    'lightshow.show.welle.name': 'Zorza',
    'lightshow.show.welle.desc': 'Wszystkie głosy pozostają rozświetlone, a jasna krawędź płynie przez zmienne kolory zorzy.',
    'lightshow.show.finale.name': 'Finał',
    'lightshow.show.finale.desc': 'Wielkie wspólne płaszczyzny, symetryczne akcenty i białe cięcia prowadzą do kulminacji.',
    'lightshow.show.prisma.name': 'Pryzmat',
    'lightshow.show.prisma.desc': 'Akordy kolorów obracają się i odbijają, aż cały chór łączy się we wspólnych neonowych płaszczyznach.',
    'lightshow.show.domino.name': 'Domino',
    'lightshow.show.domino.desc': 'Pełny dywan barw trwa, a jasne akcenty przebiegają przez niego i przechodzą we wspólne płaszczyzny.',
    'lightshow.show.dialog.name': 'Dialog',
    'lightshow.show.dialog.desc': 'Wspólne frazy przeplatają się z odpowiedziami połówek sceny oraz głosów zewnętrznych i wewnętrznych.',
    'lightshow.show.kaleidoskop.name': 'Kalejdoskop',
    'lightshow.show.kaleidoskop.desc': 'Szybkie symetryczne płaszczyzny barw ciągle układają się na nowo i regularnie łączą tutti.',

    'lightshow.syncLevel.unkritisch': 'wybacza rozjechane zegary',
    'lightshow.syncLevel.hoch': 'wybacza małe różnice',
    'lightshow.syncLevel.mittel': 'wymaga w miarę ustawionych zegarów',
    'lightshow.syncLevel.empfindlich': 'wymaga dobrze ustawionych zegarów',



    'lightshow.ntpcal.dialogTitle': 'Zsynchronizować z czasem internetowym?',
    'lightshow.ntpcal.dialogText': 'Wyśle to jednorazowe zapytanie do zegara atomowego PTB (Physikalisch-Technische Bundesanstalt, niemiecki instytut metrologiczny, uhr.ptb.de) o aktualny czas. Żadne inne dane nie zostaną przesłane — tylko to jedno zapytanie o czas.',
    'lightshow.ntpcal.dialogOk': 'Synchronizuj',
    'lightshow.ntpcal.dialogCancel': 'Anuluj',
    'lightshow.ntpcal.statusChecking': 'Odpytuję serwer czasu …',
    'lightshow.ntpcal.statusDone': 'Gotowe — korekta czasu ustawiona na {value} (czas odpowiedzi {rtt}, szacowana dokładność ±{uncertainty}).',
    'lightshow.ntpcal.statusClockError': 'Zegar urządzenia różni się o {value}. Najpierw popraw datę i godzinę urządzenia.',
    'lightshow.ntpcal.statusError': 'Serwer czasu niedostępny — spróbuj ponownie później.',
  },
};
