'use strict';

/* ==========================================================================
   STRINGS — Übersetzungstexte DE/EN/PL für data-i18n* (siehe t()/
   applyTranslations() in app.js). AP-D (ARCHITEKTUR-PLAN.md): mechanisch
   trivial auszulagern, aber semantisch an das data-i18n-Markup in index.html
   gekoppelt — deshalb vorher der Schlüsselparitäts-Selbsttest in
   runSelfTests() (DE/EN/PL exakt dieselben Schlüssel). Verwaiste Schlüssel
   einmalig vor der Auslagerung statisch geprüft (Markup + t()-Aufrufstellen
   in app.js, inklusive der wenigen mit zusammengesetztem statt wörtlichem
   Schlüssel) — keine gefunden.

   t() und applyTranslations() bleiben in app.js: beide hängen an settings
   bzw. am DOM und sind damit kein Blatt. Dieses Modul ist reine Daten, ohne
   jede Logik.
   ========================================================================== */

export const STRINGS = {
  de: {
    'nav.songs': 'Songs',
    'nav.playlists': 'Setlisten',
    'nav.player': 'Player',
    'nav.settings': 'Einstellungen',

    'tabs.loops': 'Loops',
    'tabs.lyrics': 'Lyrics',
    'tabs.notes': 'Notes',
    'tabs.sheets': 'Sheets',

    'settings.importBtn': 'Songs importieren',
    'settings.personal.title': 'Make it yours!',
    'settings.personal.tabHint': 'Reiter, der beim Öffnen eines Songs zuerst zu sehen ist.',
    'settings.personal.tabGroupAria': 'Standard-Reiter im Player',
    'settings.personal.language': 'Sprache',
    'settings.personal.accent': 'Akzentfarbe',
    'settings.personal.presentTitle': 'Textanzeige für andere',
    'settings.personal.presentHint': 'Farbe der großen Vollbildanzeige zum Mitlesen (Vollbild-Knopf beim Liedtext).',
    'settings.personal.presentThemeDark': 'Weiß auf Schwarz',
    'settings.personal.presentThemeLight': 'Schwarz auf Weiß',
    'settings.personal.searchTitle': 'Song-Suche',
    'settings.personal.searchHint': 'Dienst für das Lupen-Symbol im Player. Langes Halten fragt einmalig nach einem anderen Dienst.',
    'settings.personal.searchPrivacyHint': 'Beim Antippen der Lupe im Player gehen Songtitel (und, falls hinterlegt, der Interpret) an den hier gewählten Dienst.',

    'songsearch.dialogTitle': 'Externe Suche',
    'songsearch.dialogPrefix': 'Öffnet ',
    'songsearch.dialogSuffix': ' und sendet den Songtitel dorthin, um danach zu suchen.',
    'songsearch.dialogOk': 'Passt',
    'songsearch.dialogCancel': 'Dann nicht',

    'settings.voices.title': 'Meine Stimmen',
    'settings.voices.hint': 'Mehrfachauswahl möglich, für alle, die zwischen Stimmen wechseln. Bestimmt, welche Spuren beim Import vorausgewählt sind und welche Stimme der Player zuerst zeigt.',

    'settings.lightshow.title': 'Lichtshow',
    'settings.lightshow.hint': 'Vier kleine Bühnen-Einlagen für den Auftritt: Vollbild-Lichtfarben, die sich nach der eigenen Stimme richten und über die Systemuhr synchron laufen — ganz ohne Internet oder Verbindung zwischen den Handys.',
    'settings.lightshow.openBtn': 'Lichtshow öffnen',

    'settings.bike.title': 'Fahrradfahren-Modus',
    'settings.bike.hint': 'Bei nur einem Ohrstöpsel: Ist eine Stimme (z. B. Bass) hart auf eine Seite gemischt, hört man sie sonst je nach Ohr gar nicht.',
    'settings.bike.normal': 'Normal',
    'settings.bike.mono': 'Mono',
    'settings.bike.swap': 'Tauschen',

    'settings.screen.title': 'Bildschirm & Hintergrund',
    'settings.screen.keepOn': 'Bildschirm anlassen, solange ein Lied geöffnet ist',
    'settings.screen.keepOnAria': 'Bildschirm anlassen',
    'settings.screen.hint': 'Verhindert nur das automatische Abdunkeln bei Untätigkeit — hilft nicht, wenn du das Handy bewusst über die Ein/Aus-Taste sperrst.',
    'settings.screen.bgHelpToggle': 'Hören im Hintergrund klappt nicht?',
    'settings.screen.bgHelpIntro': 'Bricht die Wiedergabe ab, sobald du das Handy sperrst, liegt das nicht an dieser App: Android entscheidet, ob eine Web-App im Hintergrund weiterlaufen darf, und das steuern zwei Systemeinstellungen — beide lassen sich nur von Hand ändern, keine Website darf sie selbst setzen.',
    'settings.screen.step1': 'Android-Einstellungen → <strong>Apps</strong> → deinen Browser öffnen (z. B. <strong>Vanadium</strong> oder <strong>Chrome</strong> — die App, in der du „Zum Startbildschirm hinzufügen" verwendet hast).',
    'settings.screen.step2': '<strong>Akku</strong> → <strong>Nicht eingeschränkt</strong> wählen. Sonst beendet Android den Browser im Hintergrund, sobald der Bildschirm aus ist.',
    'settings.screen.step3': '<strong>Benachrichtigungen</strong> → erlauben. Android verlangt dafür eine sichtbare Benachrichtigung — ohne sie darf keine Web-App im Hintergrund weiterspielen.',
    'settings.screen.grapheneNote': 'Ohne Google-Play-Dienste — etwa auf GrapheneOS — legt „Zum Startbildschirm hinzufügen" meist nur eine Verknüpfung an, kein eigenes App-Symbol mit eigenen Berechtigungen. Die beiden Einstellungen betreffen dann den Browser selbst, nicht ein eigenes „BVG"-Symbol.',
    'settings.screen.notifyBtn': 'Benachrichtigungen für diese Seite erlauben',

    'settings.perf.title': 'Kompatibilität & Performance',
    'settings.perf.modeHint': 'Wie das Verlangsamen bei 0,85×, 0,7× und 0,6× berechnet wird.',
    'settings.perf.modeStandard': 'Standard',
    'settings.perf.modeHd': 'HD',
    'settings.perf.hdHint': 'HD rechnet den Klang selbst um, statt es dem Browser zu überlassen — deutlich sauberer bei lang gehaltenen Tönen. Kostet dafür mehr Rechenleistung. Stockt die Wiedergabe auf einem älteren Handy oder wird es warm, wieder auf Standard stellen.',
    'settings.perf.hdUnsupported': 'Dieses Gerät unterstützt HD nicht — Standard funktioniert trotzdem.',
    'settings.perf.rtLabel': 'Wiedergabetempo:',
    'settings.perf.rtSuffix': 'der Echtzeit',
    'settings.perf.rebuildBtn': 'Tonausgabe neu aufbauen',
    'settings.perf.rebuildHint': 'Klingt die Wiedergabe nach langer Zeit im Hintergrund abgehackt oder falsch, obwohl Pause/Abspielen nicht hilft: hiermit die Audioausgabe von Grund auf neu aufbauen. Wirkt nur, während gerade nichts läuft, und stoppt eine laufende Wiedergabe kurz dafür.',
    'settings.perf.rebuildDone': 'Tonausgabe neu aufgebaut.',
    'settings.perf.advToggle': 'Erweitert: Zeitdehner einstellen',
    'settings.perf.advIntro': 'Wirkt sofort, auch während der Wiedergabe. Zum Ausprobieren gedacht — die Voreinstellungen sind bewusst so gewählt, wie sie sind.',
    'settings.perf.advGroupSound': 'Klang',
    'settings.perf.advGroupCost': 'Rechenaufwand',
    'settings.perf.advFormantComp': 'Formantkorrektur',
    'settings.perf.advFormantCompHint': 'Sollte hier aus bleiben: das Resampling zieht Tonhöhe und Formanten gemeinsam nach unten, das Hochschieben holt beide gemeinsam zurück. Eingeschaltet klingt es dunkler, nicht besser.',
    'settings.perf.advFormantSemi': 'Formanten verschieben',
    'settings.perf.advFormantBase': 'Formant-Grundton',
    'settings.perf.advFormantBaseAuto': 'automatisch',
    'settings.perf.advTonality': 'Grenze für Tonhaftigkeit',
    'settings.perf.advPresetDefault': 'Standard',
    'settings.perf.advPresetCheap': 'Sparsam',
    'settings.perf.advBlock': 'Blocklänge',
    'settings.perf.advBlockAuto': 'nach Voreinstellung',
    'settings.perf.advInterval': 'Schrittweite',
    'settings.perf.advIntervalAuto': 'automatisch',
    'settings.perf.advSplit': 'Rechnung über die Quanten verteilen',
    'settings.perf.advSplitHint': 'Verteilt die Arbeit eines Analyseblocks über mehrere Render-Quanten. Kostet gemessen keine Rechenzeit, nur ein Viertel mehr Latenz — deshalb ab Werk an. Ausschalten macht die Wiedergabe direkter, aber stoßweiser.',
    'settings.perf.advLatency': 'Latenz des Zeitdehners:',
    'settings.perf.advSemitones': 'Tonhöhenkorrektur:',
    'settings.perf.advReset': 'Zurücksetzen',
    'settings.perf.advUnitSemi': 'Halbtöne',
    'settings.perf.advIsDefault': 'ab Werk',
    'settings.perf.advIsDefaultSuffix': ' · ab Werk',
    'settings.perf.advPresetIsDefault': 'Preset steht auf Voreinstellung',
    'settings.perf.advUnitLatency': 'Latenz',
    'settings.perf.advSplitInactive': 'Wirkungslos, solange ein Preset gewählt ist: die Bibliothek bestimmt dort Blocklänge und Schrittweite selbst. Eine eigene Blocklänge einstellen, dann greift der Schalter.',
    'settings.perf.advCostHint': 'Wirklich sparsamer wird es nur über die Schrittweite oder das Preset „Sparsam": eine größere Schrittweite heißt weniger Analyseblöcke je Sekunde. Die Blocklänge dagegen ändert am Rechenaufwand fast nichts, sie bestimmt Frequenzauflösung und Latenz.',
    'settings.perf.advAb': 'A/B',
    'settings.perf.advAbAria': 'Standard und eigene Einstellungen vergleichen',
    'settings.perf.advAbHint': 'Du hörst gerade die Voreinstellung zum Vergleich — deine eigenen Werte sind unverändert gespeichert.',
    'settings.perf.advCopy': 'Kopieren',
    'settings.perf.advCopied': 'Einstellungen in die Zwischenablage kopiert.',
    'settings.perf.advOn': 'an',
    'settings.perf.advOff': 'aus',

    'settings.help.title': 'Hilfe',
    'settings.help.intro': 'Die Aufnahmen kommen als ZIP-Datei aus der Dropbox in die App. Der Knopf unten zeigt Schritt für Schritt, wie das auf dem iPhone und auf Android geht.',
    'settings.help.howToBtn': 'Wie bekomme ich Songs in die App?',
    'settings.help.replayOnboarding': 'Einführung noch einmal ansehen',

    'settings.data.title': 'Daten & Sicherung',
    'settings.data.backupTitle': 'Sicherung',
    'settings.data.backupHint': 'Sichert Loops, Notizen, eigene Liedtexte, Setlisten, Einstellungen, eigene RECs und die Songliste. Beim Erstellen lässt sich auswählen, was genau enthalten sein soll — auch die (großen) Song-Audiodateien.',
    'settings.data.backupBtn': 'Backup',
    'settings.data.restoreBtn': 'Restore',
    'settings.data.printNotesBtn': 'Notizen drucken',
    'settings.data.freeSpaceTitle': 'Speicherplatz freigeben',
    'settings.data.freeSpaceHint1': 'Einzelne Songs oder Stimmen löschen. Loops, Notizen, eigene Liedtexte und Setlisten bleiben dabei erhalten.',
    'settings.data.dropAudioBtn': 'Alle Aufnahmen löschen',
    'settings.data.freeSpaceHint2': 'Entfernt nur die Audiodateien. Loops, Notizen, eigene Liedtexte, Setlisten und Einstellungen bleiben erhalten und verbinden sich beim nächsten Import wieder.',
    'settings.data.manageStorageBtn': 'Einzelne Songs verwalten',
    'settings.data.wipeTitle': 'Alles löschen',
    'settings.data.wipeHint': 'Löscht alle Songs, Aufnahmen, Loops, Notizen, eigene Liedtexte und Setlisten von diesem Gerät. Die Dateien in der Dropbox bleiben unberührt.',
    'settings.data.wipeBtn': 'Alle Daten löschen',

    'settings.about.title': 'Über die App',
    'settings.about.version': 'Version',
    'settings.about.offline': 'Offline verfügbar',
    'settings.about.privacy': 'Die App selbst stellt keine automatischen Netzwerkanfragen und sendet keine Daten — alles bleibt auf diesem Gerät. Nutzt man die optionale Liedsuche (Lupe im Player), gehen Songtitel und ggf. Interpret an den dort gewählten externen Dienst (Tidal, Spotify, Deezer, YouTube oder Google).',
    'settings.about.lame': 'MP3-Export mit <strong>lamejs</strong> (LGPL-3.0), basierend auf <strong>LAME</strong> — <a href="https://lame.sourceforge.net/" target="_blank" rel="noopener noreferrer">lame.sourceforge.net</a>.',
    'settings.about.stretch': 'Verlangsamung im Modus „HD" mit <strong>signalsmith-stretch</strong> (MIT) von Geraint Luff / Signalsmith Audio Ltd. — <a href="https://signalsmith-audio.co.uk/code/stretch/" target="_blank" rel="noopener noreferrer">signalsmith-audio.co.uk</a>.',
    'settings.about.errorLogTitle': 'Fehlerprotokoll',
    'settings.about.errorLogHint': 'Technische Fehlermeldungen der App, neueste zuerst — hilfreich beim Melden eines Problems. Bleibt nur auf diesem Gerät.',
    'settings.about.copyLogBtn': 'Protokoll kopieren',
    'settings.about.clearBtn': 'Leeren',
    'settings.about.debugLogTitle': 'Diagnose-Log',
    'settings.about.debugLogSwitch': 'Ausführliches Protokoll für schwer fassbare Fehler aufzeichnen',
    'settings.about.debugLogAria': 'Diagnose-Log aufzeichnen',
    'settings.about.debugLogHint': 'Zeichnet technische Abläufe auf (Zeitstempel, Zustände, Zahlen) — nie Songtitel, Dateinamen oder Namen. Sinnvoll direkt vor dem Nachstellen eines Problems (z. B. Import, dann Bildschirm sperren); danach hier exportieren und beim Melden mitschicken.',
    'settings.about.exportLogBtn': 'Log exportieren',

    'settings.storage.title': 'Speicher',
    'settings.storage.measuring': 'wird ermittelt …',
    'settings.storage.persistBtn': 'Dauerhafte Speicherung anfordern',

    'onb.step1of5': 'Schritt 1 von 5',
    'onb.step2of5': 'Schritt 2 von 5',
    'onb.step3of5': 'Schritt 3 von 5',
    'onb.step4of5': 'Schritt 4 von 5',
    'onb.step5of5': 'Schritt 5 von 5',
    'onb.skip': 'Überspringen',
    'onb.back': 'Zurück',
    'onb.next': 'Weiter',

    'onb.slide1.title': 'Auf den Home&#8209;Bildschirm legen',
    'onb.slide1.text': 'So startet die App wie jede andere: eigenes Symbol, kein Browserfenster, volle Bildschirmhöhe. Vor allem aber behält das System die Aufnahmen länger, wenn die App installiert ist.',

    'onb.slide2.title': 'Welche Stimme singst du?',
    'onb.slide2.text': 'Zu jedem Lied gibt es mehrere Aufnahmen — eine je Stimme und eine Gesamtmischung. Mit deiner Stimme weiß die App zweierlei:',
    'onb.slide2.li1': '<strong>Beim Import</strong> sind deine Stimme und die Gesamtmischung vorausgewählt — der Rest bleibt draußen und spart Speicherplatz.',
    'onb.slide2.li2': '<strong>Im Player</strong> klingt gleich deine Stimme, ohne dass du sie bei jedem Lied neu einstellst.',
    'onb.slide2.footnote': 'Alle Stimmen bleiben trotzdem wählbar. Änderbar unter <strong>Einstellungen&nbsp;→&nbsp;Meine Stimmen</strong>.',

    'onb.slide3.title': 'Aufnahmen dauerhaft behalten',
    'onb.slide3.text1': 'Web-Apps dürfen ihre Daten normalerweise nur „auf Probe" speichern: wird der Platz knapp oder liegt die App länger ungenutzt, räumt das System sie weg. Bei ein paar Gigabyte Aufnahmen wäre das ärgerlich.',
    'onb.slide3.text2': 'Mit einem Klick fragen wir das Betriebssystem, ob es die Daten <strong>dauerhaft</strong> behalten soll. Der Browser entscheidet selbst — ein Dialog erscheint dabei in der Regel nicht.',

    'onb.slide4.title': 'Die schwere Stelle üben',
    'onb.slide4.intro': '<strong>Abschnitt wiederholen.</strong> Im Player unter „Abschnitt üben":',
    'onb.slide4.li1': 'An der Stelle, wo es losgehen soll, auf <strong>A</strong> tippen.',
    'onb.slide4.li2': 'Am Ende der Stelle auf <strong>B</strong> tippen.',
    'onb.slide4.li3': 'Den <strong>Schalter</strong> daneben einschalten — der Abschnitt läuft jetzt in der Schleife, bis du ihn kannst.',
    'onb.slide4.li4': 'Über das <strong>Disketten-Symbol</strong> lässt sich der Abschnitt benennen und bleibt gespeichert, auch nach dem Schließen.',
    'onb.slide4.speed': '<strong>Langsamer üben.</strong> Unten rechts im Player steht die Geschwindigkeit: <strong>1,0×</strong>, <strong>0,85×</strong>, <strong>0,7×</strong> oder <strong>0,6×</strong>. Die Tonhöhe bleibt dabei gleich — es klingt langsamer, nicht tiefer. Beides zusammen ist der Kern der App: einen kurzen Abschnitt so lange langsam wiederholen, bis er sitzt.',

    'onb.slide5.title': 'Songs holen, Programm planen',
    'onb.slide5.import': '<strong>Import.</strong> Die Aufnahmen liegen im geteilten Dropbox-Ordner. Öffne ihn dafür im <strong>Browser</strong> — nicht in der Dropbox-App, die kann Ordner nicht als ZIP herunterladen —, lade ihn einmal als <strong>ZIP-Datei</strong> herunter und wählst sie unter „Einstellungen → Songs importieren" aus. Vor dem Speichern zeigt die App, was sie gefunden hat, und du hakst ab, welche Stimmen wirklich aufs Handy sollen. Jeder weitere Import <strong>ergänzt</strong> nur — Vorhandenes bleibt, fehlende Stimmen lassen sich nachladen.',
    'onb.slide5.setlists': '<strong>Setlisten.</strong> Eine Setliste ist ein Programm: die Lieder in der Reihenfolge, in der sie gesungen werden. Am Ende eines Liedes schaltet die App von selbst weiter. Der Chorleiter kann eine Setliste als schlichte Textdatei verteilen — ein Titel je Zeile —, du spielst sie unter „Setlisten" ein.',
    'onb.slide5.note': 'Alles bleibt auf diesem Gerät. Die App sendet nichts und braucht nach dem Import kein Internet mehr.',

    'common.cancel': 'Abbrechen',
    'common.close': 'Schließen',

    'import.backAria': 'Zurück zu den Einstellungen',
    'import.intro': 'Die Aufnahmen liegen im geteilten Dropbox-Ordner. Öffne Dropbox dafür im <strong>Browser</strong> (nicht in der Dropbox-App — die kann Ordner nicht als ZIP herunterladen), lade den Ordner einmal als ZIP-Datei herunter und wählst sie hier aus. Danach ist alles offline auf dem Handy — ohne Dropbox, ohne Internet.',
    'import.pickZipBtn': 'ZIP-Datei auswählen',
    'import.pickFolderBtn': 'Stattdessen einen Ordner wählen',
    'import.desktopOnly': 'Nur am Computer verfügbar.',
    'import.howToTitle': 'So kommt der Ordner aufs Handy',
    'import.howToWarning': 'Wichtig: <strong>dropbox.com im Browser öffnen, nicht die Dropbox-App</strong> — die App bietet für Ordner keinen ZIP-Download an, nur der Browser kann das.',
    'import.howToStep1': 'Im Browser bei dropbox.com anmelden, beim gewünschten Ordner auf <strong>⋮</strong> (Android) bzw. <strong>…</strong> (iPhone) tippen.',
    'import.howToStep2': '<strong>Herunterladen</strong> (Android) bzw. <strong>Exportieren → In Dateien sichern</strong> (iPhone) wählen — der Ordner landet als ZIP in „Downloads" bzw. „Dateien".',
    'import.howToStep3': 'Zurück in dieser App auf <strong>ZIP-Datei auswählen</strong> tippen und die Datei dort wählen.',
    'import.goodToKnowTitle': 'Gut zu wissen',
    'import.goodToKnow1': 'Jeder Import <strong>ergänzt</strong> die Bibliothek. Bereits vorhandene Songs bleiben erhalten.',
    'import.goodToKnow2': 'Du kannst später einzelne Lieder oder fehlende Stimmen nachladen.',
    'import.goodToKnow3': 'Vor dem Speichern kannst du auswählen, welche Stimmen aufs Handy sollen — das spart Speicherplatz.',
    'import.libraryTitle': 'Bibliothek',
    'import.libSongs': 'Songs',
    'import.libFiles': 'Dateien',
    'import.libLastImport': 'Letzter Import',
    'import.sheetTitle': 'Auswahl',
    'import.presetMine': 'Meine Stimmen',
    'import.presetFull': 'Full',
    'import.presetAll': 'Alle Stimmen',
    'import.importBtn': 'Importieren',
    'import.attachSimilarPrefix': 'Loops, Notizen und Liedtext von',
    'import.attachSimilarSuffix': 'übernehmen',

    'songs.searchPlaceholder': 'Song suchen …',
    'songs.searchAria': 'Song suchen',
    'songs.feelingLuckyAria': 'Feeling Lucky — zufälliges Lied abspielen',
    'songs.recordAria': 'Aufnehmen',

    'playlists.searchPlaceholder': 'Song suchen oder Platzhalter hinzufügen …',
    'playlists.searchAria': 'Song für die Setliste suchen',
    'playlists.emptyTitle': 'Noch keine Setlisten',
    'playlists.emptyText': 'Lege eine an oder importiere die Textdatei des Chorleiters.',

    'songs.emptyTitle': 'Noch keine Songs',
    'songs.emptyText': 'Lade die Aufnahmen aus der Dropbox als ZIP-Datei herunter und importiere sie hier.',
    'songs.notFoundTitle': 'Nichts gefunden',
    'songs.notFoundText': 'Kein Song passt zu dieser Suche.',
    'songs.createPlaceholderSuffix': 'als Platzhalter anlegen',
    'songs.createPlaceholderHint': 'Noch nicht importiertes Lied anlegen — für Liedtext, Notizen oder eine Setliste.',
    'songs.placeholderBadge': 'noch keine Aufnahme',
    'player.placeholderHint': 'Noch keine Aufnahme importiert. Liedtext und Notizen kannst du trotzdem schon speichern — sie verbinden sich automatisch beim nächsten Import.',

    'lightshow.backAria': 'Zurück zu den Einstellungen',
    'lightshow.noVoiceHint': 'Noch keine Stimme gewählt — die Show läuft vorerst im Sopran-Takt und Pink. Ändern unter <strong>Einstellungen → Meine Stimmen</strong>, oder hier nur für die Show festlegen:',
    'lightshow.voicePickerAria': 'Stimme für die Lichtshow',
    'lightshow.voicePrefix': 'Du leuchtest als',
    'lightshow.showsTitle': 'Show wählen',
    'lightshow.startBtn': 'Show starten',
    'lightshow.rehearsalLabel': 'Probelauf — startet sofort, ohne auf den Rasterpunkt zu warten',
    'lightshow.rehearsalAria': 'Probelauf',
    'lightshow.rehearsalHint': 'Steht nach dem Schließen dieser Ansicht wieder aus — sonst steht jemand auf der Bühne im Probelauf.',
    'lightshow.syncBtn': 'Uhr prüfen',
    'lightshow.hintBlock': 'Bildschirmhelligkeit vor dem Auftritt von Hand hochdrehen — das kann die App nicht selbst tun. „Datum &amp; Uhrzeit automatisch" sollte im Betriebssystem eingeschaltet bleiben. Handy während der Show nicht sperren. Vor dem Auftritt einmal zu zweit „Uhr prüfen" machen.',
    'lightshow.seizureWarning': 'Die Shows arbeiten mit hellen, wechselnden Flächen. Wer lichtempfindlich ist oder zu Anfällen neigt, macht besser nicht mit oder wählt „Sternenhimmel".',
    'lightshow.reducedMotionHint': 'Dieses Gerät bevorzugt weniger Bewegung — „Sternenhimmel" ist deshalb vorausgewählt. Die anderen Shows lassen sich trotzdem starten.',
    'lightshow.recommendedBadge': 'Empfohlen',

    'lightshow.show.sterne.name': 'Sternenhimmel',
    'lightshow.show.sterne.desc': 'Flirrendes Funkeln in der eigenen Stimmfarbe — braucht keine gut gestellte Uhr.',
    'lightshow.show.puls.name': 'Herzschlag',
    'lightshow.show.puls.desc': 'Ein Doppelschlag läuft von Sopran zu Bass durch den Chor, wird zum Ende hin kräftiger.',
    'lightshow.show.welle.name': 'Welle',
    'lightshow.show.welle.desc': 'Ein Lichtband läuft immer wieder von Sopran nach Bass, endet in einer gemeinsamen Atmung.',
    'lightshow.show.finale.name': 'Finale',
    'lightshow.show.finale.desc': 'Gruppen-Jagd, gemeinsamer Puls, ein Höhepunkt in Weiß — die einzige Show mit harten Schnitten.',

    'lightshow.syncLevel.unkritisch': 'verzeiht schiefe Uhren',
    'lightshow.syncLevel.hoch': 'verzeiht kleine Abweichungen',
    'lightshow.syncLevel.mittel': 'braucht einigermaßen gestellte Uhren',
    'lightshow.syncLevel.empfindlich': 'braucht gut gestellte Uhren',

    'lightshow.sync.instruction': 'Zwei Handys nebeneinander legen, beide dieses Bild zeigen. Laufen die Balken sichtbar versetzt, geht eine Uhr falsch.',
    'lightshow.sync.autoNote': 'Liegt ein Gerät um mehr als etwa eine halbe Sekunde daneben: nicht hier ausgleichen, sondern „Datum & Uhrzeit automatisch" im Betriebssystem einschalten. Der Handversatz ist nur die Krücke, falls das nicht geht.',
    'lightshow.sync.offsetAria': 'Handversatz',
    'lightshow.sync.resetBtn': 'Zurücksetzen',
  },
  en: {
    'nav.songs': 'Songs',
    'nav.playlists': 'Setlists',
    'nav.player': 'Player',
    'nav.settings': 'Settings',

    'tabs.loops': 'Loops',
    'tabs.lyrics': 'Lyrics',
    'tabs.notes': 'Notes',
    'tabs.sheets': 'Sheets',

    'settings.importBtn': 'Import songs',
    'settings.personal.title': 'Make it yours!',
    'settings.personal.tabHint': 'Tab that shows first when you open a song.',
    'settings.personal.tabGroupAria': 'Default tab in the player',
    'settings.personal.language': 'Language',
    'settings.personal.accent': 'Accent color',
    'settings.personal.presentTitle': 'Text display for others',
    'settings.personal.presentHint': 'Color of the full-screen display for others to read along (fullscreen button in Lyrics).',
    'settings.personal.presentThemeDark': 'White on black',
    'settings.personal.presentThemeLight': 'Black on white',
    'settings.personal.searchTitle': 'Song search',
    'settings.personal.searchHint': 'Service used by the magnifying-glass icon in the player. Long-press it to pick a different service just once.',
    'settings.personal.searchPrivacyHint': 'Tapping the magnifying glass in the player sends the song title (and artist, if known) to the service selected here.',

    'songsearch.dialogTitle': 'External search',
    'songsearch.dialogPrefix': 'Opens ',
    'songsearch.dialogSuffix': ' and sends the song title there to search for it.',
    'songsearch.dialogOk': 'Sounds good',
    'songsearch.dialogCancel': 'Not now',

    'settings.voices.title': 'My voices',
    'settings.voices.hint': 'Multiple selection possible, for anyone switching between voices. Determines which tracks are pre-selected on import and which voice the player shows first.',

    'settings.lightshow.title': 'Light show',
    'settings.lightshow.hint': 'Four small on-stage moments for the concert: full-screen light colours that follow your own voice part and stay in sync via the system clock — no internet or connection between phones needed.',
    'settings.lightshow.openBtn': 'Open light show',

    'settings.bike.title': 'Bicycle mode',
    'settings.bike.hint': 'With only one earbud in: if a voice (e.g. bass) is hard-panned to one side, you might not hear it at all depending on your ear.',
    'settings.bike.normal': 'Normal',
    'settings.bike.mono': 'Mono',
    'settings.bike.swap': 'Swap',

    'settings.screen.title': 'Screen & background',
    'settings.screen.keepOn': 'Keep the screen on while a song is open',
    'settings.screen.keepOnAria': 'Keep screen on',
    'settings.screen.hint': 'Only prevents automatic dimming from inactivity — doesn\'t help if you lock the phone yourself with the power button.',
    'settings.screen.bgHelpToggle': 'Background playback not working?',
    'settings.screen.bgHelpIntro': 'If playback stops as soon as you lock your phone, that\'s not this app\'s fault: Android decides whether a web app may keep running in the background, controlled by two system settings — both can only be changed by hand, no website can set them itself.',
    'settings.screen.step1': 'Android settings → <strong>Apps</strong> → open your browser (e.g. <strong>Vanadium</strong> or <strong>Chrome</strong> — the app you used "Add to home screen" with).',
    'settings.screen.step2': '<strong>Battery</strong> → choose <strong>Unrestricted</strong>. Otherwise Android shuts the browser down in the background as soon as the screen turns off.',
    'settings.screen.step3': '<strong>Notifications</strong> → allow. Android requires a visible notification for this — without it, no web app may keep playing in the background.',
    'settings.screen.grapheneNote': 'Without Google Play services — e.g. on GrapheneOS — "Add to home screen" usually only creates a shortcut, not a proper app icon with its own permissions. Both settings then apply to the browser itself, not a separate "BVG" icon.',
    'settings.screen.notifyBtn': 'Allow notifications for this page',

    'settings.perf.title': 'Compatibility & performance',
    'settings.perf.modeHint': 'How slowing down at 0.85×, 0.7× and 0.6× is computed.',
    'settings.perf.modeStandard': 'Standard',
    'settings.perf.modeHd': 'HD',
    'settings.perf.hdHint': 'HD recalculates the sound itself instead of leaving it to the browser — noticeably cleaner on sustained notes. Costs more processing power in return. If playback stutters on an older phone or it gets warm, switch back to Standard.',
    'settings.perf.hdUnsupported': "This device doesn't support HD — Standard still works.",
    'settings.perf.rtLabel': 'Playback speed:',
    'settings.perf.rtSuffix': 'of real time',
    'settings.perf.rebuildBtn': 'Rebuild audio output',
    'settings.perf.rebuildHint': "If playback sounds choppy or wrong after a long time in the background, and pause/play doesn't help: use this to rebuild the audio output from scratch. Only works while nothing is currently playing, and briefly stops playback to do it.",
    'settings.perf.rebuildDone': 'Audio output rebuilt.',
    'settings.perf.advToggle': 'Advanced: tune the stretcher',
    'settings.perf.advIntro': 'Takes effect immediately, even during playback. Meant for experimenting — the defaults are chosen deliberately.',
    'settings.perf.advGroupSound': 'Sound',
    'settings.perf.advGroupCost': 'Processing cost',
    'settings.perf.advFormantComp': 'Formant correction',
    'settings.perf.advFormantCompHint': 'Should stay off here: the resampling pulls pitch and formants down together, and shifting back up brings both back together. Switched on it sounds darker, not better.',
    'settings.perf.advFormantSemi': 'Shift formants',
    'settings.perf.advFormantBase': 'Formant base note',
    'settings.perf.advFormantBaseAuto': 'automatic',
    'settings.perf.advTonality': 'Tonality limit',
    'settings.perf.advPresetDefault': 'Standard',
    'settings.perf.advPresetCheap': 'Cheaper',
    'settings.perf.advBlock': 'Block length',
    'settings.perf.advBlockAuto': 'from preset',
    'settings.perf.advInterval': 'Step size',
    'settings.perf.advIntervalAuto': 'automatic',
    'settings.perf.advSplit': 'Spread computation across quanta',
    'settings.perf.advSplitHint': 'Spreads one analysis block over several render quanta. Measured to cost no extra compute, only a quarter more latency — hence on by default. Turning it off is more immediate but burstier.',
    'settings.perf.advLatency': 'Stretcher latency:',
    'settings.perf.advSemitones': 'Pitch correction:',
    'settings.perf.advReset': 'Reset',
    'settings.perf.advUnitSemi': 'semitones',
    'settings.perf.advIsDefault': 'stock',
    'settings.perf.advIsDefaultSuffix': ' · stock',
    'settings.perf.advPresetIsDefault': 'Preset is at its default',
    'settings.perf.advUnitLatency': 'latency',
    'settings.perf.advSplitInactive': 'Has no effect while a preset is selected: there the library sets block length and step size itself. Set your own block length and the switch takes effect.',
    'settings.perf.advCostHint': 'Real savings come only from the step size or the "Cheaper" preset: a larger step means fewer analysis blocks per second. Block length barely changes the cost — it sets frequency resolution and latency.',
    'settings.perf.advAb': 'A/B',
    'settings.perf.advAbAria': 'Compare standard and your own settings',
    'settings.perf.advAbHint': "You're previewing the default for comparison — your own settings are unchanged and still saved.",
    'settings.perf.advCopy': 'Copy',
    'settings.perf.advCopied': 'Settings copied to clipboard.',
    'settings.perf.advOn': 'on',
    'settings.perf.advOff': 'off',

    'settings.help.title': 'Help',
    'settings.help.intro': 'Recordings come into the app as a ZIP file from Dropbox. The button below walks through it step by step for iPhone and Android.',
    'settings.help.howToBtn': 'How do I get songs into the app?',
    'settings.help.replayOnboarding': 'Watch the intro again',

    'settings.data.title': 'Data & backup',
    'settings.data.backupTitle': 'Backup',
    'settings.data.backupHint': 'Backs up loops, notes, your own lyrics, setlists, settings, your own RECs and the song list. When creating it you can choose exactly what to include — even the (large) song audio files.',
    'settings.data.backupBtn': 'Backup',
    'settings.data.restoreBtn': 'Restore',
    'settings.data.printNotesBtn': 'Print notes',
    'settings.data.freeSpaceTitle': 'Free up storage',
    'settings.data.freeSpaceHint1': 'Delete individual songs or voices. Loops, notes, your own lyrics and setlists are kept.',
    'settings.data.dropAudioBtn': 'Delete all recordings',
    'settings.data.freeSpaceHint2': 'Only removes the audio files. Loops, notes, your own lyrics, setlists and settings are kept and reconnect on the next import.',
    'settings.data.manageStorageBtn': 'Manage individual songs',
    'settings.data.wipeTitle': 'Delete everything',
    'settings.data.wipeHint': 'Deletes all songs, recordings, loops, notes, your own lyrics and setlists from this device. Files in Dropbox stay untouched.',
    'settings.data.wipeBtn': 'Delete all data',

    'settings.about.title': 'About the app',
    'settings.about.version': 'Version',
    'settings.about.offline': 'Available offline',
    'settings.about.privacy': 'The app itself makes no automatic network requests and sends no data — everything stays on this device. Using the optional song search (magnifying glass in the player) sends the song title, and artist if known, to the external service selected there (Tidal, Spotify, Deezer, YouTube, or Google).',
    'settings.about.lame': 'MP3 export using <strong>lamejs</strong> (LGPL-3.0), based on <strong>LAME</strong> — <a href="https://lame.sourceforge.net/" target="_blank" rel="noopener noreferrer">lame.sourceforge.net</a>.',
    'settings.about.stretch': 'Slowdown in <strong>HD</strong> mode using <strong>signalsmith-stretch</strong> (MIT) by Geraint Luff / Signalsmith Audio Ltd. — <a href="https://signalsmith-audio.co.uk/code/stretch/" target="_blank" rel="noopener noreferrer">signalsmith-audio.co.uk</a>.',
    'settings.about.errorLogTitle': 'Error log',
    'settings.about.errorLogHint': 'Technical error messages from the app, newest first — helpful when reporting a problem. Stays only on this device.',
    'settings.about.copyLogBtn': 'Copy log',
    'settings.about.clearBtn': 'Clear',
    'settings.about.debugLogTitle': 'Diagnostic log',
    'settings.about.debugLogSwitch': 'Record a detailed log for hard-to-pin-down bugs',
    'settings.about.debugLogAria': 'Record diagnostic log',
    'settings.about.debugLogHint': 'Records technical events (timestamps, states, numbers) — never song titles, file names or names. Useful right before reproducing a problem (e.g. import, then lock the screen); export it here afterwards and send it along when reporting.',
    'settings.about.exportLogBtn': 'Export log',

    'settings.storage.title': 'Storage',
    'settings.storage.measuring': 'measuring …',
    'settings.storage.persistBtn': 'Request persistent storage',

    'onb.step1of5': 'Step 1 of 5',
    'onb.step2of5': 'Step 2 of 5',
    'onb.step3of5': 'Step 3 of 5',
    'onb.step4of5': 'Step 4 of 5',
    'onb.step5of5': 'Step 5 of 5',
    'onb.skip': 'Skip',
    'onb.back': 'Back',
    'onb.next': 'Next',

    'onb.slide1.title': 'Add it to your home screen',
    'onb.slide1.text': 'This makes the app start like any other: its own icon, no browser window, full screen height. Most importantly, the system keeps recordings around longer once the app is installed.',

    'onb.slide2.title': 'Which voice do you sing?',
    'onb.slide2.text': 'Every song has several recordings — one per voice, plus a full mix. Knowing your voice lets the app do two things:',
    'onb.slide2.li1': '<strong>On import</strong>, your voice and the full mix are pre-selected — everything else stays out and saves storage.',
    'onb.slide2.li2': '<strong>In the player</strong>, your voice plays right away, with no need to set it up again for every song.',
    'onb.slide2.footnote': 'All voices stay selectable regardless. Change it under <strong>Settings&nbsp;→&nbsp;My voices</strong>.',

    'onb.slide3.title': 'Keep recordings for good',
    'onb.slide3.text1': 'Web apps are normally only allowed to store data "on trial": if space gets tight or the app sits unused for a while, the system may clear it out. With a few gigabytes of recordings, that would be annoying.',
    'onb.slide3.text2': 'With one tap we ask the operating system to keep the data <strong>permanently</strong>. The browser decides for itself — usually no dialog appears.',

    'onb.slide4.title': 'Practice the hard part',
    'onb.slide4.intro': '<strong>Loop a section.</strong> In the player, under "Practice a section":',
    'onb.slide4.li1': 'Tap <strong>A</strong> where the section should start.',
    'onb.slide4.li2': 'Tap <strong>B</strong> at the end of the section.',
    'onb.slide4.li3': 'Turn on the <strong>switch</strong> next to it — the section now loops until you\'ve got it.',
    'onb.slide4.li4': 'The <strong>save icon</strong> lets you name the section, and it stays saved even after closing.',
    'onb.slide4.speed': '<strong>Practice slower.</strong> The bottom right of the player shows the speed: <strong>1.0×</strong>, <strong>0.85×</strong>, <strong>0.7×</strong> or <strong>0.6×</strong>. The pitch stays the same — it sounds slower, not lower. Together, these two are the core of the app: loop a short section slowly until it sits.',

    'onb.slide5.title': 'Get songs, plan the program',
    'onb.slide5.import': '<strong>Import.</strong> Recordings live in the shared Dropbox folder. Open it in the <strong>browser</strong> — not the Dropbox app, which can\'t download folders as a ZIP —, download it once as a <strong>ZIP file</strong> and pick it under "Settings → Import songs". Before saving, the app shows what it found, and you tick off which voices should actually go onto your phone. Every further import only <strong>adds</strong> — what\'s there stays, missing voices can be loaded later.',
    'onb.slide5.setlists': '<strong>Setlists.</strong> A setlist is a program: the songs in the order they\'re sung. The app moves on by itself at the end of a song. The choir director can hand out a setlist as a plain text file — one title per line —, which you load in under "Setlists".',
    'onb.slide5.note': 'Everything stays on this device. The app sends nothing and needs no internet after the import.',

    'common.cancel': 'Cancel',
    'common.close': 'Close',

    'import.backAria': 'Back to settings',
    'import.intro': 'Recordings live in the shared Dropbox folder. Open Dropbox in the <strong>browser</strong> for this (not the Dropbox app — it can\'t download folders as a ZIP), download the folder once as a ZIP file and pick it here. After that everything is offline on your phone — no Dropbox, no internet needed.',
    'import.pickZipBtn': 'Choose ZIP file',
    'import.pickFolderBtn': 'Choose a folder instead',
    'import.desktopOnly': 'Only available on a computer.',
    'import.howToTitle': 'Getting the folder onto your phone',
    'import.howToWarning': 'Important: <strong>open dropbox.com in the browser, not the Dropbox app</strong> — the app doesn\'t offer a ZIP download for folders, only the browser can do that.',
    'import.howToStep1': 'Sign in at dropbox.com in the browser, tap <strong>⋮</strong> (Android) or <strong>…</strong> (iPhone) on the folder you want.',
    'import.howToStep2': 'Choose <strong>Download</strong> (Android) or <strong>Export → Save to Files</strong> (iPhone) — the folder lands as a ZIP in "Downloads" or "Files".',
    'import.howToStep3': 'Back in this app, tap <strong>Choose ZIP file</strong> and pick the file there.',
    'import.goodToKnowTitle': 'Good to know',
    'import.goodToKnow1': 'Every import <strong>adds to</strong> the library. Songs already there are kept.',
    'import.goodToKnow2': 'You can load individual songs or missing voices later.',
    'import.goodToKnow3': 'Before saving you can choose which voices should go onto your phone — that saves storage.',
    'import.libraryTitle': 'Library',
    'import.libSongs': 'Songs',
    'import.libFiles': 'Files',
    'import.libLastImport': 'Last import',
    'import.sheetTitle': 'Selection',
    'import.presetMine': 'My voices',
    'import.presetFull': 'Full',
    'import.presetAll': 'All voices',
    'import.importBtn': 'Import',
    'import.attachSimilarPrefix': 'Copy loops, notes and lyrics from',
    'import.attachSimilarSuffix': 'over to this song',

    'songs.searchPlaceholder': 'Search song …',
    'songs.searchAria': 'Search song',
    'songs.feelingLuckyAria': 'Feeling Lucky — play a random song',
    'songs.recordAria': 'Record',

    'playlists.searchPlaceholder': 'Search song or add a placeholder …',
    'playlists.searchAria': 'Search a song for the setlist',
    'playlists.emptyTitle': 'No setlists yet',
    'playlists.emptyText': 'Create one, or import the choir director\'s text file.',

    'songs.emptyTitle': 'No songs yet',
    'songs.emptyText': 'Download the recordings from Dropbox as a ZIP file and import them here.',
    'songs.notFoundTitle': 'Nothing found',
    'songs.notFoundText': 'No song matches this search.',
    'songs.createPlaceholderSuffix': 'add as placeholder',
    'songs.createPlaceholderHint': 'Create a song that hasn\'t been imported yet — for lyrics, notes or a setlist.',
    'songs.placeholderBadge': 'no recording yet',
    'player.placeholderHint': 'No recording imported yet. You can still save lyrics and notes now — they connect automatically on the next import.',

    'lightshow.backAria': 'Back to settings',
    'lightshow.noVoiceHint': 'No voice part chosen yet — the show will run on soprano timing in pink for now. Change it under <strong>Settings → My voices</strong>, or set it here just for the show:',
    'lightshow.voicePickerAria': 'Voice for the light show',
    'lightshow.voicePrefix': 'You light up as',
    'lightshow.showsTitle': 'Choose a show',
    'lightshow.startBtn': 'Start show',
    'lightshow.rehearsalLabel': 'Rehearsal — starts right away instead of waiting for the grid point',
    'lightshow.rehearsalAria': 'Rehearsal',
    'lightshow.rehearsalHint': 'Turns off again once you close this view — otherwise someone could end up on stage in rehearsal mode.',
    'lightshow.syncBtn': 'Check clock',
    'lightshow.hintBlock': 'Turn up the screen brightness by hand before the concert — the app can’t do that itself. Keep "automatic date & time" switched on in the OS. Don’t lock the phone during the show. Run "Check clock" together with someone once before the concert.',
    'lightshow.seizureWarning': 'The shows use bright, changing areas of colour. If you’re light-sensitive or prone to seizures, better sit this one out or pick "Starry sky".',
    'lightshow.reducedMotionHint': 'This device prefers reduced motion — "Starry sky" is pre-selected because of that. The other shows can still be started.',
    'lightshow.recommendedBadge': 'Recommended',

    'lightshow.show.sterne.name': 'Starry sky',
    'lightshow.show.sterne.desc': 'A shimmering twinkle in your own voice colour — doesn’t need a well-set clock.',
    'lightshow.show.puls.name': 'Heartbeat',
    'lightshow.show.puls.desc': 'A double beat travels from soprano to bass through the choir, growing stronger toward the end.',
    'lightshow.show.welle.name': 'Wave',
    'lightshow.show.welle.desc': 'A band of light keeps travelling from soprano to bass, ending in a shared breath.',
    'lightshow.show.finale.name': 'Finale',
    'lightshow.show.finale.desc': 'A group chase, a shared pulse, a peak in white — the only show with hard cuts.',

    'lightshow.syncLevel.unkritisch': 'forgives clocks that run off',
    'lightshow.syncLevel.hoch': 'forgives small differences',
    'lightshow.syncLevel.mittel': 'needs reasonably set clocks',
    'lightshow.syncLevel.empfindlich': 'needs well-set clocks',

    'lightshow.sync.instruction': 'Place two phones side by side, both showing this image. If the bars visibly drift apart, one clock is off.',
    'lightshow.sync.autoNote': 'If a device is off by more than about half a second: don’t compensate here, switch on "automatic date & time" in the OS instead. The manual offset is only a crutch for when that isn’t possible.',
    'lightshow.sync.offsetAria': 'Manual offset',
    'lightshow.sync.resetBtn': 'Reset',
  },
  pl: {
    'nav.songs': 'Utwory',
    'nav.playlists': 'Setlisty',
    'nav.player': 'Odtwarzacz',
    'nav.settings': 'Ustawienia',

    'tabs.loops': 'Loopy',
    'tabs.lyrics': 'Tekst',
    'tabs.notes': 'Notatki',
    'tabs.sheets': 'Nuty',

    'settings.importBtn': 'Importuj utwory',
    'settings.personal.title': 'Make it yours!',
    'settings.personal.tabHint': 'Zakładka widoczna jako pierwsza po otwarciu utworu.',
    'settings.personal.tabGroupAria': 'Domyślna zakładka w odtwarzaczu',
    'settings.personal.language': 'Język',
    'settings.personal.accent': 'Kolor akcentu',
    'settings.personal.presentTitle': 'Wyświetlanie tekstu dla innych',
    'settings.personal.presentHint': 'Kolor dużego, pełnoekranowego wyświetlacza do wspólnego czytania (przycisk pełnego ekranu przy tekście).',
    'settings.personal.presentThemeDark': 'Biały na czarnym',
    'settings.personal.presentThemeLight': 'Czarny na białym',
    'settings.personal.searchTitle': 'Wyszukiwanie utworu',
    'settings.personal.searchHint': 'Usługa używana przez ikonę lupy w odtwarzaczu. Długie przytrzymanie pozwala jednorazowo wybrać inną usługę.',
    'settings.personal.searchPrivacyHint': 'Dotknięcie lupy w odtwarzaczu wysyła tytuł utworu (a jeśli jest znany, także wykonawcę) do usługi wybranej tutaj.',

    'songsearch.dialogTitle': 'Wyszukiwanie zewnętrzne',
    'songsearch.dialogPrefix': 'Otwiera ',
    'songsearch.dialogSuffix': ' i wysyła tam tytuł utworu, aby go wyszukać.',
    'songsearch.dialogOk': 'Pasuje',
    'songsearch.dialogCancel': 'Nie teraz',

    'settings.voices.title': 'Moje głosy',
    'settings.voices.hint': 'Można wybrać kilka — dla osób śpiewających różnymi głosami. Decyduje, które ścieżki są wstępnie zaznaczone przy imporcie i który głos odtwarzacz pokazuje jako pierwszy.',

    'settings.lightshow.title': 'Pokaz świateł',
    'settings.lightshow.hint': 'Cztery krótkie sceniczne wstawki na koncert: pełnoekranowe kolory światła dopasowane do własnego głosu, zsynchronizowane przez zegar systemowy — bez internetu i bez połączenia między telefonami.',
    'settings.lightshow.openBtn': 'Otwórz pokaz świateł',

    'settings.bike.title': 'Tryb rowerowy',
    'settings.bike.hint': 'Przy jednej słuchawce: jeśli głos (np. bas) jest mocno przesunięty na jedną stronę, w drugim uchu może być w ogóle niesłyszalny.',
    'settings.bike.normal': 'Normalny',
    'settings.bike.mono': 'Mono',
    'settings.bike.swap': 'Zamień',

    'settings.screen.title': 'Ekran i tło',
    'settings.screen.keepOn': 'Ekran włączony, dopóki utwór jest otwarty',
    'settings.screen.keepOnAria': 'Ekran włączony',
    'settings.screen.hint': 'Zapobiega tylko automatycznemu przygaszaniu przy bezczynności — nie pomoże, gdy sam zablokujesz telefon przyciskiem.',
    'settings.screen.bgHelpToggle': 'Odtwarzanie w tle nie działa?',
    'settings.screen.bgHelpIntro': 'Jeśli odtwarzanie przerywa się zaraz po zablokowaniu telefonu, to nie wina tej aplikacji: Android decyduje, czy aplikacja webowa może działać w tle, a sterują tym dwa ustawienia systemowe — oba trzeba zmienić ręcznie, żadna strona nie może ustawić ich sama.',
    'settings.screen.step1': 'Ustawienia Androida → <strong>Aplikacje</strong> → otwórz swoją przeglądarkę (np. <strong>Vanadium</strong> lub <strong>Chrome</strong> — tę, w której użyto „Dodaj do ekranu głównego").',
    'settings.screen.step2': '<strong>Bateria</strong> → wybierz <strong>Bez ograniczeń</strong>. W przeciwnym razie Android zamknie przeglądarkę w tle, gdy tylko ekran zgaśnie.',
    'settings.screen.step3': '<strong>Powiadomienia</strong> → zezwól. Android wymaga widocznego powiadomienia — bez niego żadna aplikacja webowa nie może grać w tle.',
    'settings.screen.grapheneNote': 'Bez usług Google Play — np. na GrapheneOS — „Dodaj do ekranu głównego" zwykle tworzy tylko skrót, a nie osobną ikonę aplikacji z własnymi uprawnieniami. Oba ustawienia dotyczą wtedy samej przeglądarki, nie osobnej ikony „BVG".',
    'settings.screen.notifyBtn': 'Zezwól na powiadomienia dla tej strony',

    'settings.perf.title': 'Kompatybilność i wydajność',
    'settings.perf.modeHint': 'Jak liczone jest spowolnienie przy 0,85×, 0,7× i 0,6×.',
    'settings.perf.modeStandard': 'Standard',
    'settings.perf.modeHd': 'HD',
    'settings.perf.hdHint': 'HD sam przelicza dźwięk, zamiast zostawiać to przeglądarce — wyraźnie czyściej przy długich dźwiękach. Kosztuje to więcej mocy obliczeniowej. Jeśli odtwarzanie się zacina na starszym telefonie albo się nagrzewa, wróć do Standardu.',
    'settings.perf.hdUnsupported': 'To urządzenie nie obsługuje HD — Standard nadal działa.',
    'settings.perf.rtLabel': 'Tempo odtwarzania:',
    'settings.perf.rtSuffix': 'czasu rzeczywistego',
    'settings.perf.rebuildBtn': 'Odbuduj wyjście audio',
    'settings.perf.rebuildHint': 'Jeśli odtwarzanie brzmi urywanie lub źle po długim czasie w tle, a pauza/odtwarzanie nie pomaga: użyj tego, aby odbudować wyjście audio od nowa. Działa tylko, gdy nic akurat nie gra, i na chwilę zatrzymuje odtwarzanie.',
    'settings.perf.rebuildDone': 'Wyjście audio odbudowane.',
    'settings.perf.advToggle': 'Zaawansowane: ustawienia rozciągacza',
    'settings.perf.advIntro': 'Działa natychmiast, także w trakcie odtwarzania. Do eksperymentów — ustawienia domyślne są dobrane świadomie.',
    'settings.perf.advGroupSound': 'Brzmienie',
    'settings.perf.advGroupCost': 'Obciążenie',
    'settings.perf.advFormantComp': 'Korekta formantów',
    'settings.perf.advFormantCompHint': 'Powinna tu zostać wyłączona: resampling obniża wysokość i formanty razem, a podniesienie przywraca oba razem. Włączona brzmi ciemniej, nie lepiej.',
    'settings.perf.advFormantSemi': 'Przesuń formanty',
    'settings.perf.advFormantBase': 'Ton podstawowy formantów',
    'settings.perf.advFormantBaseAuto': 'automatycznie',
    'settings.perf.advTonality': 'Granica tonalności',
    'settings.perf.advPresetDefault': 'Standard',
    'settings.perf.advPresetCheap': 'Oszczędny',
    'settings.perf.advBlock': 'Długość bloku',
    'settings.perf.advBlockAuto': 'wg ustawienia',
    'settings.perf.advInterval': 'Krok',
    'settings.perf.advIntervalAuto': 'automatycznie',
    'settings.perf.advSplit': 'Rozłóż obliczenia na kwanty',
    'settings.perf.advSplitHint': 'Rozkłada pracę jednego bloku analizy na kilka kwantów renderowania. Zmierzono, że nie kosztuje mocy, tylko ćwierć więcej opóźnienia — dlatego jest domyślnie włączone.',
    'settings.perf.advLatency': 'Opóźnienie rozciągacza:',
    'settings.perf.advSemitones': 'Korekta wysokości:',
    'settings.perf.advReset': 'Resetuj',
    'settings.perf.advUnitSemi': 'półtonów',
    'settings.perf.advIsDefault': 'fabrycznie',
    'settings.perf.advIsDefaultSuffix': ' · fabrycznie',
    'settings.perf.advPresetIsDefault': 'Ustawienie domyślne',
    'settings.perf.advUnitLatency': 'opóźnienia',
    'settings.perf.advSplitInactive': 'Bez efektu, gdy wybrane jest ustawienie wstępne: biblioteka sama dobiera tam długość bloku i krok. Ustaw własną długość bloku, wtedy przełącznik zadziała.',
    'settings.perf.advCostHint': 'Realne oszczędności daje tylko krok albo ustawienie „Oszczędny": większy krok to mniej bloków analizy na sekundę. Długość bloku prawie nie zmienia obciążenia — decyduje o rozdzielczości i opóźnieniu.',
    'settings.perf.advAb': 'A/B',
    'settings.perf.advAbAria': 'Porównaj ustawienie standardowe z własnym',
    'settings.perf.advAbHint': 'Słuchasz teraz ustawienia domyślnego do porównania — twoje własne wartości pozostają zapisane bez zmian.',
    'settings.perf.advCopy': 'Kopiuj',
    'settings.perf.advCopied': 'Ustawienia skopiowane do schowka.',
    'settings.perf.advOn': 'wł.',
    'settings.perf.advOff': 'wył.',

    'settings.help.title': 'Pomoc',
    'settings.help.intro': 'Nagrania trafiają do aplikacji jako plik ZIP z Dropboxa. Poniższy przycisk pokazuje krok po kroku, jak zrobić to na iPhonie i na Androidzie.',
    'settings.help.howToBtn': 'Jak wgrać utwory do aplikacji?',
    'settings.help.replayOnboarding': 'Obejrzyj wprowadzenie ponownie',

    'settings.data.title': 'Dane i kopia zapasowa',
    'settings.data.backupTitle': 'Kopia zapasowa',
    'settings.data.backupHint': 'Zapisuje loopy, notatki, własne teksty, setlisty, ustawienia, własne nagrania (REC) i listę utworów. Przy tworzeniu można wybrać, co dokładnie ma być uwzględnione — także (duże) pliki audio utworów.',
    'settings.data.backupBtn': 'Kopia zapasowa',
    'settings.data.restoreBtn': 'Przywróć',
    'settings.data.printNotesBtn': 'Drukuj notatki',
    'settings.data.freeSpaceTitle': 'Zwolnij miejsce',
    'settings.data.freeSpaceHint1': 'Usuń pojedyncze utwory lub głosy. Loopy, notatki, własne teksty i setlisty pozostają zachowane.',
    'settings.data.dropAudioBtn': 'Usuń wszystkie nagrania',
    'settings.data.freeSpaceHint2': 'Usuwa tylko pliki audio. Loopy, notatki, własne teksty, setlisty i ustawienia pozostają zachowane i połączą się ponownie przy kolejnym imporcie.',
    'settings.data.manageStorageBtn': 'Zarządzaj pojedynczymi utworami',
    'settings.data.wipeTitle': 'Usuń wszystko',
    'settings.data.wipeHint': 'Usuwa wszystkie utwory, nagrania, loopy, notatki, własne teksty i setlisty z tego urządzenia. Pliki w Dropboxie pozostają nietknięte.',
    'settings.data.wipeBtn': 'Usuń wszystkie dane',

    'settings.about.title': 'O aplikacji',
    'settings.about.version': 'Wersja',
    'settings.about.offline': 'Dostępna offline',
    'settings.about.privacy': 'Sama aplikacja nie wysyła automatycznie żadnych zapytań sieciowych ani danych — wszystko pozostaje na tym urządzeniu. Korzystanie z opcjonalnego wyszukiwania utworu (lupka w odtwarzaczu) przesyła tytuł utworu, a jeśli jest znany, także wykonawcę, do wybranej tam zewnętrznej usługi (Tidal, Spotify, Deezer, YouTube lub Google).',
    'settings.about.lame': 'Eksport MP3 z użyciem <strong>lamejs</strong> (LGPL-3.0), opartego na <strong>LAME</strong> — <a href="https://lame.sourceforge.net/" target="_blank" rel="noopener noreferrer">lame.sourceforge.net</a>.',
    'settings.about.stretch': 'Spowolnienie w trybie <strong>HD</strong> z użyciem <strong>signalsmith-stretch</strong> (MIT) autorstwa Geraint Luff / Signalsmith Audio Ltd. — <a href="https://signalsmith-audio.co.uk/code/stretch/" target="_blank" rel="noopener noreferrer">signalsmith-audio.co.uk</a>.',
    'settings.about.errorLogTitle': 'Dziennik błędów',
    'settings.about.errorLogHint': 'Techniczne komunikaty błędów aplikacji, najnowsze na górze — pomocne przy zgłaszaniu problemu. Pozostaje tylko na tym urządzeniu.',
    'settings.about.copyLogBtn': 'Kopiuj dziennik',
    'settings.about.clearBtn': 'Wyczyść',
    'settings.about.debugLogTitle': 'Dziennik diagnostyczny',
    'settings.about.debugLogSwitch': 'Zapisuj szczegółowy dziennik dla trudnych do uchwycenia błędów',
    'settings.about.debugLogAria': 'Zapisuj dziennik diagnostyczny',
    'settings.about.debugLogHint': 'Zapisuje techniczne zdarzenia (znaczniki czasu, stany, liczby) — nigdy tytuły utworów, nazwy plików ani nazwiska. Przydatne tuż przed odtworzeniem problemu (np. import, potem zablokowanie ekranu); potem wyeksportuj tutaj i dołącz przy zgłoszeniu.',
    'settings.about.exportLogBtn': 'Eksportuj dziennik',

    'settings.storage.title': 'Pamięć',
    'settings.storage.measuring': 'sprawdzanie …',
    'settings.storage.persistBtn': 'Poproś o trwałe przechowywanie',

    'onb.step1of5': 'Krok 1 z 5',
    'onb.step2of5': 'Krok 2 z 5',
    'onb.step3of5': 'Krok 3 z 5',
    'onb.step4of5': 'Krok 4 z 5',
    'onb.step5of5': 'Krok 5 z 5',
    'onb.skip': 'Pomiń',
    'onb.back': 'Wstecz',
    'onb.next': 'Dalej',

    'onb.slide1.title': 'Dodaj do ekranu głównego',
    'onb.slide1.text': 'Dzięki temu aplikacja startuje jak każda inna: własna ikona, bez okna przeglądarki, pełny ekran. Przede wszystkim system dłużej przechowuje nagrania, gdy aplikacja jest zainstalowana.',

    'onb.slide2.title': 'Jakim głosem śpiewasz?',
    'onb.slide2.text': 'Do każdego utworu jest kilka nagrań — jedno na głos i jeden pełny miks. Znając twój głos, aplikacja wie dwie rzeczy:',
    'onb.slide2.li1': '<strong>Przy imporcie</strong> twój głos i pełny miks są wstępnie zaznaczone — reszta zostaje pominięta, co oszczędza miejsce.',
    'onb.slide2.li2': '<strong>W odtwarzaczu</strong> od razu słychać twój głos, bez ustawiania go na nowo przy każdym utworze.',
    'onb.slide2.footnote': 'Wszystkie głosy nadal można wybrać. Zmienisz to w <strong>Ustawienia&nbsp;→&nbsp;Moje głosy</strong>.',

    'onb.slide3.title': 'Zachowaj nagrania na stałe',
    'onb.slide3.text1': 'Aplikacje webowe zwykle mogą przechowywać dane tylko „na próbę": gdy zabraknie miejsca albo aplikacja długo nie jest używana, system może je usunąć. Przy kilku gigabajtach nagrań byłoby to uciążliwe.',
    'onb.slide3.text2': 'Jednym dotknięciem pytamy system operacyjny, czy może zachować dane <strong>na stałe</strong>. Przeglądarka decyduje sama — zwykle bez żadnego okna dialogowego.',

    'onb.slide4.title': 'Ćwicz trudny fragment',
    'onb.slide4.intro': '<strong>Powtarzaj fragment.</strong> W odtwarzaczu, w sekcji „Ćwicz fragment":',
    'onb.slide4.li1': 'Dotknij <strong>A</strong> w miejscu, gdzie fragment ma się zaczynać.',
    'onb.slide4.li2': 'Dotknij <strong>B</strong> na końcu fragmentu.',
    'onb.slide4.li3': 'Włącz <strong>przełącznik</strong> obok — fragment gra teraz w pętli, aż go opanujesz.',
    'onb.slide4.li4': '<strong>Ikona dyskietki</strong> pozwala nazwać fragment i zapisuje go na stałe, nawet po zamknięciu.',
    'onb.slide4.speed': '<strong>Ćwicz wolniej.</strong> W prawym dolnym rogu odtwarzacza jest prędkość: <strong>1,0×</strong>, <strong>0,85×</strong>, <strong>0,7×</strong> lub <strong>0,6×</strong>. Wysokość dźwięku pozostaje taka sama — brzmi wolniej, nie niżej. Oba te elementy razem to sedno aplikacji: powtarzać krótki fragment wolno, aż zasiądzie.',

    'onb.slide5.title': 'Pobierz utwory, zaplanuj program',
    'onb.slide5.import': '<strong>Import.</strong> Nagrania znajdują się we współdzielonym folderze Dropbox. Otwórz go w <strong>przeglądarce</strong> — nie w aplikacji Dropbox, która nie umie pobrać folderu jako ZIP —, pobierz go raz jako plik <strong>ZIP</strong> i wybierz go w „Ustawienia → Importuj utwory". Przed zapisaniem aplikacja pokazuje, co znalazła, a ty zaznaczasz, które głosy naprawdę mają trafić na telefon. Każdy kolejny import tylko <strong>dodaje</strong> — to, co jest, zostaje, brakujące głosy można doładować później.',
    'onb.slide5.setlists': '<strong>Setlisty.</strong> Setlista to program: utwory w kolejności, w jakiej są śpiewane. Po zakończeniu utworu aplikacja sama przechodzi dalej. Prowadzący chór może rozesłać setlistę jako zwykły plik tekstowy — jeden tytuł na linię —, a ty wczytujesz ją w „Setlisty".',
    'onb.slide5.note': 'Wszystko pozostaje na tym urządzeniu. Aplikacja niczego nie wysyła i po imporcie nie potrzebuje już internetu.',

    'common.cancel': 'Anuluj',
    'common.close': 'Zamknij',

    'import.backAria': 'Wróć do ustawień',
    'import.intro': 'Nagrania znajdują się we współdzielonym folderze Dropbox. Otwórz Dropbox w <strong>przeglądarce</strong> (nie w aplikacji Dropbox — ta nie potrafi pobrać folderu jako ZIP), pobierz folder raz jako plik ZIP i wybierz go tutaj. Potem wszystko działa offline na telefonie — bez Dropboxa, bez internetu.',
    'import.pickZipBtn': 'Wybierz plik ZIP',
    'import.pickFolderBtn': 'Wybierz zamiast tego folder',
    'import.desktopOnly': 'Dostępne tylko na komputerze.',
    'import.howToTitle': 'Jak przenieść folder na telefon',
    'import.howToWarning': 'Ważne: <strong>otwórz dropbox.com w przeglądarce, nie aplikację Dropbox</strong> — aplikacja nie oferuje pobierania folderów jako ZIP, tylko przeglądarka to potrafi.',
    'import.howToStep1': 'Zaloguj się na dropbox.com w przeglądarce, dotknij <strong>⋮</strong> (Android) lub <strong>…</strong> (iPhone) przy wybranym folderze.',
    'import.howToStep2': 'Wybierz <strong>Pobierz</strong> (Android) lub <strong>Eksportuj → Zapisz w Plikach</strong> (iPhone) — folder trafi jako ZIP do „Pobrane" lub „Pliki".',
    'import.howToStep3': 'Wróć do tej aplikacji, dotknij <strong>Wybierz plik ZIP</strong> i wskaż tam ten plik.',
    'import.goodToKnowTitle': 'Warto wiedzieć',
    'import.goodToKnow1': 'Każdy import <strong>uzupełnia</strong> bibliotekę. Utwory, które już tam są, pozostają.',
    'import.goodToKnow2': 'Pojedyncze utwory lub brakujące głosy możesz doładować później.',
    'import.goodToKnow3': 'Przed zapisaniem możesz wybrać, które głosy mają trafić na telefon — to oszczędza miejsce.',
    'import.libraryTitle': 'Biblioteka',
    'import.libSongs': 'Utwory',
    'import.libFiles': 'Pliki',
    'import.libLastImport': 'Ostatni import',
    'import.sheetTitle': 'Wybór',
    'import.presetMine': 'Moje głosy',
    'import.presetFull': 'Full',
    'import.presetAll': 'Wszystkie głosy',
    'import.importBtn': 'Importuj',
    'import.attachSimilarPrefix': 'Przenieś loopy, notatki i tekst z',
    'import.attachSimilarSuffix': 'do tego utworu',

    'songs.searchPlaceholder': 'Szukaj utworu …',
    'songs.searchAria': 'Szukaj utworu',
    'songs.feelingLuckyAria': 'Feeling Lucky — odtwórz losowy utwór',
    'songs.recordAria': 'Nagraj',

    'playlists.searchPlaceholder': 'Szukaj utworu lub dodaj placeholder …',
    'playlists.searchAria': 'Szukaj utworu do setlisty',
    'playlists.emptyTitle': 'Jeszcze brak setlist',
    'playlists.emptyText': 'Utwórz jedną albo zaimportuj plik tekstowy od prowadzącego chór.',

    'songs.emptyTitle': 'Jeszcze brak utworów',
    'songs.emptyText': 'Pobierz nagrania z Dropboxa jako plik ZIP i zaimportuj je tutaj.',
    'songs.notFoundTitle': 'Nic nie znaleziono',
    'songs.notFoundText': 'Żaden utwór nie pasuje do tego wyszukiwania.',
    'songs.createPlaceholderSuffix': 'dodaj jako placeholder',
    'songs.createPlaceholderHint': 'Utwórz jeszcze niezaimportowany utwór — na tekst, notatki lub do setlisty.',
    'songs.placeholderBadge': 'jeszcze bez nagrania',
    'player.placeholderHint': 'Nagranie nie zostało jeszcze zaimportowane. Możesz już teraz zapisać tekst i notatki — połączą się automatycznie przy kolejnym imporcie.',

    'lightshow.backAria': 'Wróć do ustawień',
    'lightshow.noVoiceHint': 'Nie wybrano jeszcze głosu — pokaz na razie działa w tempie sopranu, w kolorze różowym. Zmień to w <strong>Ustawienia → Moje głosy</strong>, albo ustaw tylko dla pokazu tutaj:',
    'lightshow.voicePickerAria': 'Głos na pokaz świateł',
    'lightshow.voicePrefix': 'Świecisz jako',
    'lightshow.showsTitle': 'Wybierz pokaz',
    'lightshow.startBtn': 'Uruchom pokaz',
    'lightshow.rehearsalLabel': 'Próba — zaczyna od razu, bez czekania na punkt siatki czasowej',
    'lightshow.rehearsalAria': 'Próba',
    'lightshow.rehearsalHint': 'Po zamknięciu tego widoku znowu jest wyłączona — inaczej ktoś mógłby stanąć na scenie w trybie próby.',
    'lightshow.syncBtn': 'Sprawdź zegar',
    'lightshow.hintBlock': 'Przed koncertem podkręć jasność ekranu ręcznie — aplikacja nie może zrobić tego sama. „Automatyczna data i godzina" powinna zostać włączona w systemie. Nie blokuj telefonu podczas pokazu. Przed występem zrób raz we dwoje „Sprawdź zegar".',
    'lightshow.seizureWarning': 'Pokazy operują jasnymi, zmieniającymi się barwami. Osoby wrażliwe na światło lub podatne na napady lepiej niech nie biorą udziału albo wybiorą „Rozgwieżdżone niebo".',
    'lightshow.reducedMotionHint': 'To urządzenie preferuje mniej ruchu — dlatego wybrano wstępnie „Rozgwieżdżone niebo". Pozostałe pokazy nadal można uruchomić.',
    'lightshow.recommendedBadge': 'Polecane',

    'lightshow.show.sterne.name': 'Rozgwieżdżone niebo',
    'lightshow.show.sterne.desc': 'Migoczące skrzenie we własnym kolorze głosu — nie wymaga dobrze ustawionego zegara.',
    'lightshow.show.puls.name': 'Bicie serca',
    'lightshow.show.puls.desc': 'Podwójne uderzenie biegnie od sopranu do basu przez chór, narasta ku końcowi.',
    'lightshow.show.welle.name': 'Fala',
    'lightshow.show.welle.desc': 'Pasmo światła wciąż biegnie od sopranu do basu, kończy się wspólnym oddechem.',
    'lightshow.show.finale.name': 'Finał',
    'lightshow.show.finale.desc': 'Pościg grup, wspólny puls, szczyt w bieli — jedyny pokaz z ostrymi cięciami.',

    'lightshow.syncLevel.unkritisch': 'wybacza rozjechane zegary',
    'lightshow.syncLevel.hoch': 'wybacza małe różnice',
    'lightshow.syncLevel.mittel': 'wymaga w miarę ustawionych zegarów',
    'lightshow.syncLevel.empfindlich': 'wymaga dobrze ustawionych zegarów',

    'lightshow.sync.instruction': 'Połóż dwa telefony obok siebie, oba pokazujące ten obraz. Jeśli paski wyraźnie się rozjeżdżają, jeden zegar się myli.',
    'lightshow.sync.autoNote': 'Jeśli urządzenie myli się o więcej niż pół sekundy: nie wyrównuj tego tutaj, tylko włącz „Automatyczną datę i godzinę" w systemie. Ręczne przesunięcie to tylko podpórka, gdy to niemożliwe.',
    'lightshow.sync.offsetAria': 'Ręczne przesunięcie',
    'lightshow.sync.resetBtn': 'Resetuj',
  },
};
